/* Extra practice decks (always available on the Cards tab).
   History content follows the OCR J410 specification content lists for the options Chesterton teaches:
   International Relations 1918–1975, USA 1919–1948, Migration to Britain c.1000–c.2010,
   Impact of Empire 1688–c.1730, Spitalfields. Format: [prompt, answer]. */
RG.decks = {
  histDates: [
    // Conflict and co-operation 1918–1939
    ['Armistice ends the First World War', '11 November 1918'],
    ['Treaty of Versailles signed', '28 June 1919'],
    ['League of Nations first meets', 'January 1920'],
    ['League settles the Åland Islands dispute', '1921'],
    ['League settles Upper Silesia', '1921'],
    ['Washington Naval Conference limits navies', '1921–22'],
    ['Corfu Incident', '1923'],
    ['Dawes Plan', '1924'],
    ['Locarno Treaties', '1925'],
    ['League stops the Greek–Bulgarian dispute', '1925'],
    ['Germany joins the League of Nations', '1926'],
    ['Kellogg–Briand Pact', '1928'],
    ['Young Plan', '1929'],
    ['Wall Street Crash (Black Tuesday)', '29 October 1929'],
    ['Japan invades Manchuria', 'September 1931'],
    ['World Disarmament Conference', '1932–34'],
    ['Lytton Report condemns Japan', '1932'],
    ['Hitler becomes Chancellor', 'January 1933'],
    ['Japan leaves the League of Nations', '1933'],
    ['Germany leaves the League and the Disarmament Conference', 'October 1933'],
    ['Hitler announces conscription and rearmament', 'March 1935'],
    ['Italy invades Abyssinia', 'October 1935'],
    ['Hoare–Laval Pact', 'December 1935'],
    ['Rhineland remilitarised', 'March 1936'],
    ['Anschluss with Austria', 'March 1938'],
    ['Munich Agreement (Sudetenland)', 'September 1938'],
    ['Germany takes the rest of Czechoslovakia', 'March 1939'],
    ['Nazi–Soviet Pact', 'August 1939'],
    ['Germany invades Poland', '1 September 1939'],
    ['Britain and France declare war on Germany', '3 September 1939'],
    // Cold War in Europe 1945–1961
    ['Yalta Conference', 'February 1945'],
    ['Potsdam Conference', 'July–August 1945'],
    ['Churchill\'s "Iron Curtain" speech', 'March 1946'],
    ['Truman Doctrine', 'March 1947'],
    ['Marshall Plan announced', 'June 1947'],
    ['Berlin Blockade begins', 'June 1948'],
    ['Berlin Blockade ends', 'May 1949'],
    ['NATO formed', 'April 1949'],
    ['West Germany (FRG) and East Germany (GDR) created', '1949'],
    ['Warsaw Pact formed', 'May 1955'],
    ['Berlin Wall built', 'August 1961'],
    // Cold War confrontations 1954–1975
    ['French defeat at Dien Bien Phu', '1954'],
    ['Geneva Accords divide Vietnam at the 17th parallel', '1954'],
    ['Castro takes power in Cuba', '1959'],
    ['Bay of Pigs invasion', 'April 1961'],
    ['Cuban Missile Crisis', 'October 1962'],
    ['Test Ban Treaty', '1963'],
    ['Gulf of Tonkin incident', 'August 1964'],
    ['Operation Rolling Thunder begins', 'March 1965'],
    ['Tet Offensive', 'January 1968'],
    ['My Lai Massacre', 'March 1968'],
    ['Kent State shootings', 'May 1970'],
    ['Paris Peace Accords', 'January 1973'],
    ['Fall of Saigon', 'April 1975'],
    // USA 1919–1948
    ['Palmer Raids', '1919–20'],
    ['Prohibition begins (18th Amendment)', 'January 1920'],
    ['Women get the vote (19th Amendment)', '1920'],
    ['Emergency Quota Act limits immigration', '1921'],
    ['Sheppard-Towner Act', '1921'],
    ['Fordney–McCumber Tariff', '1922'],
    ['Immigration Act sets national quotas', '1924'],
    ['Sacco and Vanzetti executed', '1927'],
    ['St Valentine\'s Day Massacre', 'February 1929'],
    ['Bonus Army marches on Washington', '1932'],
    ['Roosevelt elected President', 'November 1932'],
    ['The Hundred Days (First New Deal)', 'March–June 1933'],
    ['Prohibition ends (21st Amendment)', 'December 1933'],
    ['Second New Deal: WPA, Social Security Act, Wagner Act', '1935'],
    ['Roosevelt\'s plan to "pack" the Supreme Court', '1937'],
    ['Executive Order 8802 bans discrimination in defence industries', 'June 1941'],
    ['Pearl Harbor attacked', '7 December 1941'],
    ['Executive Order 9066: Japanese Americans interned', 'February 1942'],
    ['Detroit Race Riots', 'June 1943'],
    ['US armed forces desegregated', '1948'],
    // Migration to Britain
    ['Norman Conquest', '1066'],
    ['Massacre of Jews at York (Clifford\'s Tower)', '1190'],
    ['Jews expelled from England by Edward I', '1290'],
    ['Peasants\' Revolt — Flemings attacked in London', '1381'],
    ['Alien subsidy tax on foreigners', '1440'],
    ['East India Company founded', '1600'],
    ['Jews readmitted under Cromwell', '1656'],
    ['Revocation of the Edict of Nantes — Huguenots flee France', '1685'],
    ['Palatine refugees arrive from Germany', '1709'],
    ['Somerset case', '1772'],
    ['Irish Great Famine', '1845–52'],
    ['Chartist leader William Cuffay transported', '1849'],
    ['Naturalisation Act', '1870'],
    ['Pogroms drive Eastern European Jews west', 'from 1881'],
    ['Aliens Act', '1905'],
    ['Status of Aliens Act', '1914'],
    ['Battle of Cable Street', 'October 1936'],
    ['Kindertransport', '1938–39'],
    ['Polish Resettlement Act', '1947'],
    ['Empire Windrush arrives; British Nationality Act', '1948'],
    ['Notting Hill riots', '1958'],
    ['Commonwealth Immigrants Act', '1962'],
    ['Bristol Bus Boycott', '1963'],
    ['First Race Relations Act', '1965'],
    ['Enoch Powell\'s "Rivers of Blood" speech', 'April 1968'],
    ['Immigration Act', '1971'],
    ['Idi Amin expels Ugandan Asians', '1972'],
    ['Race Relations Act sets up the Commission for Racial Equality', '1976'],
    ['Murder of Altab Ali in Whitechapel', 'May 1978'],
    ['British Nationality Act (redefines citizenship)', '1981'],
    ['EU enlargement brings migrants from Eastern Europe', '2004'],
    // Impact of Empire 1688–c.1730 + Spitalfields
    ['Glorious Revolution', '1688'],
    ['Bill of Rights', '1689'],
    ['East India Company establishes Kolkata (Calcutta)', '1690'],
    ['Battle of the Boyne', '1690'],
    ['Treaty of Limerick', '1691'],
    ['Massacre of Glencoe', '1692'],
    ['Bank of England founded', '1694'],
    ['Royal African Company loses its monopoly', '1698'],
    ['Darien Scheme', '1698–1700'],
    ['Act of Union (England and Scotland)', '1707'],
    ['Treaty of Utrecht (Britain gains the Asiento)', '1713'],
    ['Hanoverian succession — George I becomes king', '1714'],
    ['Jacobite Rebellion', '1715'],
    ['South Sea Bubble', '1719–20'],
    ['59 Brick Lane built as a Huguenot chapel', '1743'],
    ['59 Brick Lane becomes a synagogue', '1898'],
    ['59 Brick Lane becomes a mosque', '1976'],
  ],
  histPeople: [
    ['Woodrow Wilson', 'US President at Versailles — 14 Points, self-determination, League of Nations'],
    ['Georges Clemenceau', 'French leader at Versailles — wanted revenge and security'],
    ['David Lloyd George', 'British PM at Versailles — wanted a middle way'],
    ['Gustav Stresemann', 'German Foreign Minister — Locarno and joining the League'],
    ['Neville Chamberlain', 'British PM — appeasement, Munich Agreement 1938'],
    ['"Guilty Men" (1940)', 'Early book blaming the appeasers for the war'],
    ['Joseph Stalin', 'Soviet leader — Eastern Europe, Berlin Blockade'],
    ['Harry Truman', 'US President from 1945 — containment, Truman Doctrine'],
    ['George Marshall', 'US Secretary of State — the Marshall Plan'],
    ['Nikita Khrushchev', 'Soviet leader — Berlin Wall, Cuban Missile Crisis'],
    ['John F. Kennedy', 'US President — Bay of Pigs, Cuban Missile Crisis'],
    ['Fidel Castro', 'Leader of Cuba after the 1959 revolution'],
    ['Ho Chi Minh', 'Communist leader of North Vietnam'],
    ['Ngo Dinh Diem', 'US-backed leader of South Vietnam'],
    ['Lyndon B. Johnson', 'US President who escalated the Vietnam War'],
    ['Richard Nixon', 'US President — Vietnamisation and withdrawal'],
    ['Herbert Hoover', 'Republican President when the Depression began'],
    ['Franklin D. Roosevelt', 'US President from 1933 — the New Deal'],
    ['Al Capone', 'Chicago gangster who grew rich from bootlegging'],
    ['A. Mitchell Palmer', 'Attorney General behind the Palmer Raids'],
    ['Marcus Garvey', 'Led the UNIA — Black pride and self-reliance'],
    ['NAACP', 'Fought racial discrimination through the courts and campaigns'],
    ['Huey Long', 'New Deal critic — "Share Our Wealth"'],
    ['Father Coughlin', 'Radio priest who attacked the New Deal'],
    ['Dr Francis Townsend', 'Campaigned for pensions for the elderly'],
    ['"Rosie the Riveter"', 'Symbol of women doing war work'],
    ['John Blanke', 'Black trumpeter at the Tudor court'],
    ['Olaudah Equiano', 'Formerly enslaved writer and abolitionist'],
    ['William Cuffay', 'Black Chartist leader, transported in 1849'],
    ['Huguenots', 'French Protestant refugees — silk weavers in Spitalfields'],
    ['Palatines', 'German Protestant refugees who arrived in 1709'],
    ['Lascars', 'Indian and other Asian sailors on East India Company ships'],
    ['Ayahs', 'Indian nannies who came with families returning from India'],
    ['Denization', 'An old way for a foreigner to gain some rights of a subject'],
    ['Enoch Powell', 'MP whose 1968 "Rivers of Blood" speech attacked immigration'],
    ['Idi Amin', 'Ugandan dictator who expelled Ugandan Asians in 1972'],
    ['Altab Ali', 'Bangladeshi worker murdered in 1978 — a symbol of anti-racism'],
    ['Charles Booth', 'Made colour-coded poverty maps of London'],
    ['William III', 'Took the throne with Mary in the Glorious Revolution'],
    ['George I', 'First Hanoverian king (1714)'],
    ['Jacobites', 'Supporters of the exiled Stuart kings'],
    ['The Asiento', 'Right to supply enslaved Africans to Spanish colonies'],
    ['Appeasement', 'Giving in to demands to avoid war'],
    ['Containment', 'US policy to stop the spread of communism'],
    ['Domino theory', 'If one country fell to communism, its neighbours would follow'],
    ['Vietnamisation', 'Handing the fighting to South Vietnam as US troops left'],
    ['Laissez-faire', 'Government stays out of the economy'],
    ['Hire purchase', 'Buying goods now and paying in instalments'],
    ['Speakeasy', 'Illegal bar during Prohibition'],
    ['Hooverville', 'Shanty town built by the homeless in the Depression'],
    ['Alphabet agencies', 'New Deal bodies known by initials (CCC, TVA, WPA…)'],
    ['Double V campaign', 'Victory over fascism abroad and racism at home'],
  ],
};
