/* English Language — AQA 8700; English Literature — OCR J352 (Chesterton exams page + KS4 English map 2026-27) */
RG.subjects.push({
  id: 'englang', name: 'English Language', board: 'AQA', spec: '8700', quals: 1, share: 0.10,
  link: 'https://www.aqa.org.uk/subjects/english/gcse/english-language-8700',
  papers: [
    { id: 'el1', code: '8700/1', name: 'Paper 1 · Explorations in Creative Reading & Writing', date: '2027-05-24', time: 'am', dur: 105 },
    { id: 'el2', code: '8700/2', name: 'Paper 2 · Writers\' Viewpoints & Perspectives', date: '2027-06-08', time: 'am', dur: 105 }
  ],
  structure: [
    'Two papers, 1h 45m each, 80 marks, 50% each. Section A Reading (40), Section B Writing (40).',
    'Paper 1: one unseen 20th/21st-century fiction extract. Q1 (4), Q2 (8), Q3 (8), Q4 (20), Q5 creative writing (40).',
    'Paper 2: two linked non-fiction sources (one 19th century). Q1 (4), Q2 (8), Q3 (12), Q4 (16), Q5 viewpoint writing (40).',
    'Spoken Language endorsement is assessed separately (taught Y11 autumn at Chesterton).'
  ],
  technique: [
    'Read the questions before the source, so you read with a purpose.',
    'Stick to time: roughly 1 minute per mark, and 45 minutes for Q5 including 5 minutes of planning.',
    'Q5 is half the paper — never leave it until you have 20 minutes left. Some students do it first.',
    'Use short embedded quotations, then zoom in on a single word and its effect.',
    'Leave 5 minutes to proofread Q5: 16 of its 40 marks are for technical accuracy.'
  ],
  resources: [
    ['AQA 8700 spec, past papers & mark schemes', 'https://www.aqa.org.uk/subjects/english/gcse/english-language-8700'],
    ['BBC Bitesize GCSE English Language', 'https://www.bbc.co.uk/bitesize/levels/z98jmp3']
  ],
  topics: [
    { id: 'el-p1q1', n: 'P1 Q1 & P2 Q1 — retrieval (4 marks)', p: ['el1', 'el2'], w: 1,
      pts: ['P1 Q1: list four things from the lines given. You can quote or paraphrase. Stay inside the line numbers.',
        'P2 Q1: shade the four TRUE statements from eight. Check each against the exact lines.',
        'Spend about 5 minutes. These are the easiest marks on the paper.'],
      cards: [['How long for Q1?', 'About 5 minutes'], ['P2 Q1 task', 'Choose four true statements from eight']],
      ex: 'Do Q1 from two past papers in 5 minutes each and mark them.' },
    { id: 'el-lang', n: 'Language analysis (P1 Q2, P2 Q3)', p: ['el1', 'el2'], w: 3,
      pts: ['P1 Q2 (8 marks, ~10 min) and P2 Q3 (12 marks, ~15 min): HOW the writer uses language.',
        'Cover words and phrases, language techniques, and sentence forms.',
        'Structure: point → short quotation → name the technique → zoom in on one word → effect on the reader → link to the question.',
        'Useful terms: verb, adjective, adverb, simile, metaphor, personification, semantic field, sibilance, juxtaposition, hyperbole, rhetorical question, imperative, listing, short sentences.',
        'Top band: "perceptive" and "detailed". Explore more than one interpretation of a word.'],
      cards: [['What three things should a language answer cover?', 'Words/phrases, language techniques, sentence forms'], ['Define semantic field', 'A group of words linked by a topic or theme'],
        ['What turns a clear answer into a perceptive one?', 'Exploring layered or alternative meanings of single words'], ['Time for P2 Q3', 'About 15 minutes (12 marks)']],
      ex: 'Pick an extract and write a 10-minute Q2 answer with 3 zoomed-in points. Mark it against the AQA levels.' },
    { id: 'el-struct', n: 'Structure (P1 Q3)', p: ['el1'], w: 2,
      pts: ['8 marks, ~10 minutes. Whole-text focus: how the writer structures the extract to interest the reader.',
        'Track the focus: what are we shown at the beginning, how does it shift in the middle, and where does it end up?',
        'Features: shift in focus or perspective, zoom in/out, flashback, foreshadowing, dialogue, one-line paragraph, cyclical structure, a turning point, contrast between openings and endings.',
        'Always say WHY the writer does it: tension, sympathy, mystery, or a change of mood.'],
      cards: [['What does P1 Q3 focus on?', 'Structure — the order and shifts across the whole extract'], ['Name four structural features', 'Shift in focus, flashback, one-line paragraph, cyclical structure']],
      ex: 'Annotate an extract with beginning / middle / end focus shifts, then write a 10-minute Q3.' },
    { id: 'el-eval', n: 'Evaluation (P1 Q4)', p: ['el1'], w: 3,
      pts: ['20 marks, ~25 minutes. A student\'s statement about part of the text — how far do you agree?',
        'Evaluate: give your view, and support it with quotations and analysis of the writer\'s methods.',
        'Use the statement\'s own words in your topic sentences.',
        'Top band: "critical, detailed evaluation" and "convincing" judgement. Consider the reader\'s response.'],
      cards: [['Marks and time for P1 Q4', '20 marks, about 25 minutes'], ['What must an evaluation include?', 'Your judgement on the statement + evidence + analysis of methods']],
      ex: 'Write a full 25-minute Q4 from a past paper and self-mark against the levels.' },
    { id: 'el-compare', n: 'Summary & comparison (P2 Q2, Q4)', p: ['el2'], w: 3,
      pts: ['Q2 (8 marks): summary of differences or similarities using BOTH sources. Make inferences, and do not analyse language.',
        'Q4 (16 marks, ~20 min): compare the writers\' perspectives AND how they convey them (methods), across both whole sources.',
        'Use comparative connectives: whereas, similarly, in contrast, both writers.',
        'Infer attitudes from context (for example, a 19th-century writer\'s view of children or work).'],
      cards: [['What does P2 Q2 test?', 'Summary and inference across two sources (no language analysis needed)'], ['What must P2 Q4 compare?', 'Perspectives AND the methods used to convey them'],
        ['Four comparative connectives', 'Whereas, similarly, in contrast, likewise']],
      ex: 'Do Q2 and Q4 from one past Paper 2 in 30 minutes.' },
    { id: 'el-creative', n: 'Creative writing (P1 Q5)', p: ['el1'], w: 3,
      pts: ['40 marks: 24 for content and organisation, 16 for technical accuracy. About 45 minutes (5 min plan, 35 min write, 5 min check).',
        'Choice: a description (often from a picture) or a story.',
        'Plan the shape: a drop-in opening, a zoom from wide to detail, a single moment, a cyclical ending, or a flashback.',
        'Show, don\'t tell. Use all five senses and precise vocabulary. Vary sentence openings and lengths.',
        'Use a range of punctuation deliberately: ; : — … ? !',
        'Narrative: few characters, one setting, one main event. Don\'t try to fit in a whole film plot.'],
      cards: [['How are Q5 marks split?', '24 content & organisation, 16 technical accuracy'], ['Five-part structure for a description', 'e.g. wide shot → detail → person → shift in time/weather → return to the start'],
        ['Why use a cyclical structure?', 'Gives a satisfying, crafted ending that echoes the opening']],
      ex: 'Plan in 5 minutes and write for 35 minutes from a past-paper picture prompt. Proofread for 5.' },
    { id: 'el-viewpoint', n: 'Viewpoint writing (P2 Q5)', p: ['el2'], w: 3,
      pts: ['40 marks: 24 + 16. Write an article, letter, speech, essay or leaflet giving your view on a statement.',
        'Match form, audience and purpose — for example a formal letter to a head teacher, or a lively speech to students.',
        'Methods: direct address, anecdote, facts and statistics, rhetorical questions, repetition, the rule of three, a counter-argument then rebuttal, and emotive language.',
        'Paragraph plan: hook → 3–4 arguments (strongest last) → counter-argument → powerful call to action.',
        'Keep your view clear and consistent. Nuance is fine, sitting on the fence is not.'],
      cards: [['Five forms that can appear in P2 Q5', 'Article, letter, speech, essay, leaflet'], ['Why include a counter-argument?', 'Shows balance, then rebutting it makes your view stronger'],
        ['Layout of a formal letter', 'Dear Sir/Madam … Yours faithfully (or Dear Mr X … Yours sincerely)']],
      ex: 'Write a full 45-minute Q5 from a past Paper 2 statement.' },
    { id: 'el-spag', n: 'Technical accuracy (SPaG)', p: ['el1', 'el2'], w: 2,
      pts: ['No comma splices: two full sentences need a full stop, a semicolon or a conjunction.',
        'Apostrophes: possession (the dog\'s bone, the dogs\' bones) and omission (it\'s = it is). "Its" shows possession.',
        'Homophones: their/there/they\'re, your/you\'re, where/were/wear, affect/effect.',
        'Colon introduces a list or explanation. Semicolon joins two linked full sentences.',
        'New paragraph for a new time, place, topic or speaker (TiPToP).'],
      cards: [['it\'s vs its', 'it\'s = it is / it has; its = belonging to it'], ['What is a comma splice?', 'Joining two full sentences with only a comma'],
        ['When do you start a new paragraph?', 'New time, place, topic or person speaking']],
      ex: 'Proofread your last piece of writing and fix 10 errors. Then do 5 minutes of semicolon/colon sentences.' }
  ]
});

RG.subjects.push({
  id: 'englit', name: 'English Literature', board: 'OCR', spec: 'J352', quals: 1, share: 0.10,
  link: 'https://www.ocr.org.uk/qualifications/gcse/english-literature-j352-from-2015/',
  papers: [
    { id: 'lit1', code: 'J352/01', name: 'Paper 1 · Modern & literary heritage texts', date: '2027-05-12', time: 'am', dur: 120 },
    { id: 'lit2', code: 'J352/02', name: 'Paper 2 · Poetry & Shakespeare', date: '2027-05-19', time: 'am', dur: 120 }
  ],
  structure: [
    'Two papers, 2 hours each, 80 marks, 50% each. Closed book — learn your quotations.',
    'Paper 1 Section A (An Inspector Calls): (a) compare an extract with an unseen extract from another text (20 marks, ~45 min) and (b) a question on the wider play (20 marks, ~30 min).',
    'Paper 1 Section B (19th-century novel — compulsory, 25% of the GCSE): one 40-mark question, extract-based OR an essay. Chesterton\'s KS4 English map lists Jekyll and Hyde (taught Year 10, Spring 1) — check with your English teacher that this is your class\'s novel.',
    'Paper 2 Section A (Conflict cluster): (a) compare a named anthology poem with an unseen poem (20) and (b) explore another poem from the cluster (20).',
    'Paper 2 Section B (Romeo and Juliet): one 40-mark question — extract-based OR an essay.'
  ],
  technique: [
    'Start every answer with a thesis sentence that answers the question directly.',
    'Every paragraph needs a quotation, analysis of the method (AO2) and a link to context (AO3) that serves the argument.',
    'Write about the writer as a craftsman: "Priestley uses…", "Stevenson presents…".',
    'In comparison questions, compare in every paragraph, not in separate halves.',
    'Learn 8–10 flexible quotations per text that fit many themes.'
  ],
  resources: [
    ['OCR J352 spec, anthology & past papers', 'https://www.ocr.org.uk/qualifications/gcse/english-literature-j352-from-2015/'],
    ['OCR past paper finder', 'https://www.ocr.org.uk/qualifications/past-paper-finder/']
  ],
  topics: [
    { id: 'aic-plot', n: 'An Inspector Calls — plot & context', p: ['lit1'], w: 3, from: '2026-09-02',
      pts: ['Written by J.B. Priestley in 1945 and first staged in 1945–46. Set in 1912 in Brumley, at the Birlings\' engagement dinner for Sheila and Gerald.',
        'Inspector Goole reveals the chain: Mr Birling sacked Eva Smith for leading a strike for higher wages → Sheila had her sacked from Milwards out of jealousy → Gerald kept her (as Daisy Renton) as his mistress → Mrs Birling refused her help at the charity committee → Eric got her pregnant and stole money.',
        'Final twists: there may be no Inspector Goole, and no single girl — then a phone call says a girl has died and an inspector is on his way.',
        'Context: Priestley was a socialist. 1912 had a rigid class system and no welfare state. By 1945 audiences had lived through two world wars, and Labour won in 1945 promising a welfare state.',
        'Dramatic irony: Birling calls the Titanic "unsinkable" and says there will be no war, so the audience distrusts his capitalist views.'],
      cards: [['When was An Inspector Calls written and set?', 'Written 1945, set 1912'], ['Why did Mr Birling sack Eva?', 'She led a strike for higher wages'],
        ['Why did Sheila get Eva sacked?', 'Jealousy — Eva smiled when Sheila tried on a dress'], ['What name did Eva use with Gerald?', 'Daisy Renton'],
        ['What is the effect of the Titanic line?', 'Dramatic irony — makes Birling look foolish, undermining capitalism'], ['What was Priestley\'s political message?', 'Socialism / collective social responsibility']],
      ex: 'Retell the chain of events from memory in 5 minutes, then answer a (b)-style question in 30 minutes.' },
    { id: 'aic-chars', n: 'An Inspector Calls — characters & themes', p: ['lit1'], w: 3, from: '2026-09-02',
      pts: ['Inspector Goole: Priestley\'s mouthpiece and moral voice. Controls the pace ("one line of inquiry at a time"). Final speech: "We are members of one body."',
        'Mr Birling: self-made capitalist, "hard-headed", obsessed with a knighthood. Refuses to learn.',
        'Mrs Birling: class prejudice, cold. She blames the father of the child, which unknowingly condemns Eric.',
        'Sheila: changes the most, representing the hopeful young generation. Eric: drinks and is weak, but accepts responsibility.',
        'Gerald: upper class, partly sympathetic, but relieved when the Inspector seems a hoax — he sides with the older generation.',
        'Themes: social responsibility, class, gender, age (young vs old), guilt. Stage directions: lighting changes from "pink and intimate" to "brighter and harder".'],
      cards: [['Which character changes most?', 'Sheila'], ['What does the Inspector represent?', 'Priestley\'s views / social conscience / possibly a supernatural figure'],
        ['Why is the lighting change important?', 'Pink = rosy, comfortable illusion; bright and hard = the harsh truth exposed'], ['Which generation does Gerald side with?', 'The older generation (the Birling parents)']],
      ex: 'Make a table: each character — 3 quotations — what Priestley uses them to show. Then practise an unseen-extract comparison (a).' },
    { id: 'jh-plot', n: 'Jekyll and Hyde — plot & context', p: ['lit1'], w: 3,
      pts: ['Check with your teacher: Chesterton\'s KS4 English map lists Jekyll and Hyde as the 19th-century novel (Paper 1 Section B, compulsory). If your class studied a different novel, tell me and it will be swapped.',
        'Published 1886 by Robert Louis Stevenson. Narrated mainly through Utterson, a respectable lawyer.',
        'Key events: Enfield\'s "Story of the Door" (Hyde tramples a girl) → Jekyll\'s will → Hyde murders Sir Danvers Carew with a cane → Lanyon\'s shock and death → the Last Night (Poole and Utterson break in and find Hyde dead) → Lanyon\'s and Jekyll\'s letters reveal the truth.',
        'Victorian context: public respectability and reputation, repressed desires, fear of degeneration after Darwin, advances in science, and a religious backlash.',
        'Gothic genre: fog-bound London, secrecy, doubles, the monstrous, and locked doors.',
        'The narrative withholds the truth until the last chapters, creating mystery.'],
      cards: [['When was Jekyll and Hyde published?', '1886'], ['Who does Hyde murder?', 'Sir Danvers Carew (an MP)'], ['Who narrates most of the novella?', 'Mostly follows Utterson (third person), then letters from Lanyon and Jekyll'],
        ['Which Victorian idea made Hyde\'s "ape-like" description frightening?', 'Darwin\'s evolution — fear of degeneration'], ['What is a key Gothic feature of the setting?', 'Fog / darkness hiding London\'s secrets']],
      ex: 'Write a 45-minute answer to a past-paper Jekyll and Hyde question, with a thesis and context in each paragraph.' },
    { id: 'jh-themes', n: 'Jekyll and Hyde — characters & themes', p: ['lit1'], w: 3,
      pts: ['Duality: everyone has good and evil within. Jekyll\'s statement says "man is not truly one, but truly two".',
        'Hyde: described as "troglodytic" and "ape-like", he produces an indescribable disgust. He represents unrestrained desire and violence.',
        'Utterson: rational, loyal, protective of reputations — he keeps secrets. Lanyon: traditional science; the truth kills him.',
        'Reputation and secrecy: gentlemen avoid gossip. The door and the laboratory are symbols of hidden selves.',
        'Science vs religion: Jekyll\'s "transcendental" science breaks moral limits.'],
      cards: [['Theme shown by the two sides of Jekyll\'s house', 'Duality — a respectable front hiding a sinister back door'], ['Why does Utterson avoid investigating openly?', 'To protect Jekyll\'s reputation — Victorian respectability'],
        ['How does Lanyon represent traditional science?', 'Dismisses Jekyll\'s ideas as "unscientific balderdash"; dies after seeing the transformation']],
      ex: 'Learn 8 quotations using the "look, cover, write, check" method, then plan three essays in 5 minutes each.' },
    { id: 'rj-plot', n: 'Romeo and Juliet — plot & context', p: ['lit2'], w: 3,
      pts: ['Prologue (a sonnet): "star-crossed lovers" — we know from the start that they will die.',
        'Act 1: street fight, the Capulet party, the lovers meet. Act 2: balcony scene, secret marriage by Friar Laurence.',
        'Act 3: Tybalt kills Mercutio, Romeo kills Tybalt and is banished. Capulet orders Juliet to marry Paris.',
        'Act 4: the Friar\'s sleeping potion. Act 5: the message fails, Romeo poisons himself, Juliet stabs herself, and the families reconcile.',
        'Context: Elizabethan patriarchy (daughters obeyed fathers, arranged marriage), honour and duelling, religion (suicide as a sin), belief in fate and the stars.'],
      cards: [['Who kills Mercutio?', 'Tybalt'], ['Why is Romeo banished?', 'He kills Tybalt'], ['Why does the Friar marry them?', 'Hopes it will end the feud'],
        ['What does "star-crossed" suggest?', 'Fate — their destiny is written in the stars'], ['Why is Capulet\'s anger at Juliet shocking to us but normal then?', 'Patriarchal society expected obedience from daughters']],
      ex: 'Summarise each act in two lines from memory. Then answer an extract-based past-paper question in 45 minutes.' },
    { id: 'rj-themes', n: 'Romeo and Juliet — characters & themes', p: ['lit2'], w: 3,
      pts: ['Love: Petrarchan love for Rosaline vs true love for Juliet. Their first meeting is a shared sonnet (religious imagery — "pilgrims").',
        'Conflict and violence: the feud, Tybalt\'s hatred ("I hate the word / As I hate hell, all Montagues and thee"), and Mercutio\'s "A plague o\' both your houses!"',
        'Fate vs free will, time and haste, youth vs age, light and dark imagery ("It is the east, and Juliet is the sun").',
        'Juliet grows from an obedient daughter into a decisive woman who defies her father. Romeo is impulsive.',
        'The Nurse (comic, then betrays Juliet), the Friar (well-meaning but causes the tragedy), Capulet (loving, then tyrannical).'],
      cards: [['Mercutio\'s dying curse', '"A plague o\' both your houses!"'], ['What imagery does Romeo use for Juliet in the balcony scene?', 'Light — "Juliet is the sun"'],
        ['How does the Nurse betray Juliet?', 'Advises her to marry Paris'], ['Which theme does haste link to?', 'Time / impulsiveness leading to tragedy']],
      ex: 'Plan 3 essays (Juliet, conflict, fate) in 5 minutes each, then write one in full.' },
    { id: 'poem-heritage', n: 'Conflict poems: Envy · Boat Stealing · Sennacherib · Certain Slant of Light · Songs for the People', p: ['lit2'], w: 3,
      pts: ['Envy (Mary Lamb): a moral poem using a rose tree that should not envy other flowers — be content with yourself. Inner conflict.',
        'Boat Stealing (Wordsworth, Prelude): a boy steals a boat at night, and a huge mountain peak seems to stride after him. Guilt, and nature as a moral power.',
        'The Destruction of Sennacherib (Byron): the Assyrian army is destroyed overnight by the Angel of Death. Galloping rhythm, and "like the wolf on the fold".',
        'There\'s a Certain Slant of Light (Dickinson): winter light brings "Heavenly Hurt" — internal, spiritual despair. Dashes, capitals.',
        'Songs for the People (Frances E. W. Harper): the speaker wants poetry that comforts the poor and weary and ends "war and crime", not martial songs.',
        'For each poem learn: the speaker and situation, the type of conflict, 3 key quotations, 2 methods, and a partner poem to compare with.'],
      cards: [['What is the conflict in Boat Stealing?', 'Guilt / the boy vs nature\'s power'], ['Simile at the start of Sennacherib', '"The Assyrian came down like the wolf on the fold"'],
        ['What kind of conflict is in "A Certain Slant of Light"?', 'Internal / spiritual despair'], ['What does the speaker want in Songs for the People?', 'Songs to comfort the poor and bring peace, not war']],
      ex: 'Write one 20-mark (b) answer on one of these poems in 30 minutes.' },
    { id: 'poem-war', n: 'Conflict poems: Vergissmeinnicht · What Were They Like? · Lament · Flag · Colonization in Reverse', p: ['lit2'], w: 3,
      pts: ['Vergissmeinnicht (Keith Douglas): soldiers return three weeks after a battle and find a dead German soldier with a photo of his girlfriend Steffi. The lover and the killer are the same man.',
        'What Were They Like? (Levertov): question-and-answer form about the Vietnamese people destroyed by war. Answers in the past tense ("It is not remembered").',
        'Lament (Gillian Clarke): the Gulf War\'s environmental and human damage (the green turtle, the cormorant in "funeral silk"). A list of elegies.',
        'Flag (John Agard): questions and answers show that a "piece of cloth" makes people fight and die. Satirical, with a warning ending.',
        'Colonization in Reverse (Louise Bennett): Jamaican patois, and a humorous, ironic view of Jamaicans emigrating to Britain — "colonising" it in reverse.',
        'Comparison pairs: Vergissmeinnicht + What Were They Like? (human cost), Flag + Colonization in Reverse (identity and nation).'],
      cards: [['What does the soldier find in Vergissmeinnicht?', 'A photo of his girlfriend Steffi, signed "Vergissmeinnicht" (forget me not)'],
        ['Form of What Were They Like?', 'Questions and answers'], ['Which war is Lament about?', 'The 1991 Gulf War'], ['Language used in Colonization in Reverse', 'Jamaican patois']],
      ex: 'Compare one of these poems with an unseen poem for 45 minutes (the (a)-style task).' },
    { id: 'poem-modern', n: 'Conflict poems: Honour Killing · Partition · Papa-T · We Lived Happily during the War · Thirteen', p: ['lit2'], w: 3,
      pts: ['Honour Killing (Imtiaz Dharker): the speaker strips away layers of imposed identity (clothing, religion, culture) to find her true self. Conflict between self and society.',
        'Partition (Sujata Bhatt): family memory of the 1947 Partition of India, refugees and violence. Guilt and helplessness at suffering seen but not stopped.',
        'We Lived Happily during the War (Ilya Kaminsky): comfortable citizens stay passive while their country bombs others. Complicity, protest "not enough".',
        'Papa-T (Fred D\'Aguiar): addressed to the poet\'s grandfather in Guyana, remembered reciting Tennyson\'s "The Charge of the Light Brigade" in "no-nonsense recitals". The imperial battle blurs with the Guyanese jungle and family life (he threatens the children with a "good lickin\'"). Intertextual: unlike Tennyson\'s soldiers, who just "do and die", for the poet "to hear" is "to disobey".',
        'Thirteen (Caleb Femi): second person ("you") and future tense predict the life of a Black boy in North Peckham who has just turned thirteen — he will be wrongly suspected and questioned by police, contrasted with a police officer who once visited his primary school and promised a bright future. Extended metaphor of stars: supernovas are dying stars, and black holes. Conflict: prejudice and lost innocence.',
        'For each: the speaker, the type of conflict (personal, political, cultural), 3 quotations, 2 methods, and a partner poem.'],
      cards: [['What does the speaker remove in Honour Killing?', 'Layers of imposed identity (clothes/veil, culture, religion) to reveal herself'], ['Historical event in Partition', '1947 Partition of India'],
        ['Central idea of We Lived Happily during the War', 'Complicity — ordinary people ignored suffering caused by their country'], ['Which five poems were added in OCR\'s 2022 update (exams from 2024)?', 'Papa-T, Songs for the People, We Lived Happily during the War, Colonization in Reverse, Thirteen'],
        ['Who is "Papa-T"?', 'The poet\'s grandfather (also a nod to Tennyson) — he recited "The Charge of the Light Brigade"'],
        ['What does the speaker predict for the boy in Thirteen?', 'He will be falsely suspected by police — his bright promise dimmed by prejudice'],
        ['Extended metaphor in Thirteen', 'Stars — supernovas (dying stars) and black holes']],
      ex: 'Fill in a one-page grid for all 15 cluster poems (speaker, conflict, 3 quotes, methods), then test yourself on it.' },
    { id: 'lit-unseen', n: 'Unseen extracts & comparison skills', p: ['lit1', 'lit2'], w: 2,
      pts: ['Both papers include an unseen comparison: an unseen drama/prose extract in P1(a) and an unseen poem in P2(a).',
        'Read the unseen twice. Identify the speaker, situation, tone and turning point before quoting.',
        'Compare in each paragraph: similarity or difference → quote from both → methods → effect.',
        'Don\'t bring in wider knowledge of your set text in the (a) extract comparisons — focus on the two extracts.'],
      cards: [['Where do unseen comparisons appear?', 'P1 Section A (a) — unseen extract; P2 Section A (a) — unseen poem'], ['Best comparison structure', 'Integrated: compare both texts in every paragraph']],
      ex: 'Do one full (a) comparison from a past paper in 45 minutes.' }
  ]
});
