/* German — AQA GCSE German 8662 (new specification, first exams 2026) — Chesterton exams page + Y10/Y11 German maps */
RG.subjects.push({
  id: 'german', name: 'German', board: 'AQA', spec: '8662', quals: 1, share: 0.12,
  tierable: true,
  link: 'https://www.aqa.org.uk/subjects/german/gcse/german-8662',
  papers: [
    { id: 'de-ls', code: '8662/L + R', name: 'Listening + Reading (same session)', date: '2027-05-10', time: 'pm', dur: 105 },
    { id: 'de-w', code: '8662/W', name: 'Writing', date: '2027-05-18', time: 'pm', dur: 75 },
    { id: 'de-s', code: '8662/S', name: 'Speaking (with your teacher — date set by school, before 24 May)', date: '2027-04-26', time: '—', dur: 15, approx: true }
  ],
  structure: [
    'Four papers, 25% each. Tier (Foundation or Higher) is the same for all four.',
    'Listening: F 35 min / H 45 min, including a dictation section. Reading: F 45 min / H 1 hour, including translation into English. Both are on Monday 10 May (pm).',
    'Writing: F 1h 10m / H 1h 15m, including translation into German. Higher has a translation, a ~90-word task and a ~150-word task (with choices).',
    'Speaking: role-play, reading aloud + short conversation, and photo card + conversation, after supervised preparation. Conducted by the school before 24 May 2027 — the date shown here is a placeholder.',
    'Themes: 1 People & lifestyle · 2 Popular culture · 3 Communication & the world around us. AQA publishes a defined vocabulary list — it is worth learning.'
  ],
  technique: [
    'Vocabulary is the single biggest lever: 10–15 minutes of flashcards every day beats a weekly cram.',
    'Every writing and speaking answer should use three time frames (past, present, future), opinions with reasons (weil …), and one "wow" structure (wenn ich … wäre, würde ich …).',
    'Listening: read the questions in the reading time, predict the vocabulary, and don\'t change an answer just because a word is repeated.',
    'Dictation: know the German sound–spelling rules (ei = "eye", ie = "ee", w = "v", v = "f", sch, ch, ß, umlauts).',
    'Translation: translate every word, check verb position and tense, and don\'t leave blanks.'
  ],
  resources: [
    ['AQA 8662 spec, vocabulary list & sample papers', 'https://www.aqa.org.uk/subjects/german/gcse/german-8662'],
    ['BBC Bitesize GCSE German', 'https://www.bbc.co.uk/bitesize/levels/z98jmp3']
  ],
  topics: [
    { id: 'de-rel', n: 'Theme 1 · Identity & relationships', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Describe family and friends: Ich verstehe mich gut mit meiner Mutter, weil sie geduldig ist.',
        'Relationships and conflict: Mein Bruder geht mir auf die Nerven. Wir streiten uns oft über …',
        'Role models: Mein Vorbild ist …, weil er/sie hilfsbereit und selbstbewusst ist.',
        'Future: Ich möchte (nicht) heiraten / Kinder haben, weil …'],
      cards: [['sich verstehen mit (+ dative)', 'to get on with'], ['auf die Nerven gehen', 'to get on (someone\'s) nerves'], ['das Vorbild', 'role model'],
        ['geduldig', 'patient'], ['zuverlässig', 'reliable'], ['eifersüchtig', 'jealous'], ['geschieden', 'divorced'], ['ledig', 'single (unmarried)'],
        ['der Stiefvater', 'stepfather'], ['sich streiten', 'to argue'], ['I get on well with my sister', 'Ich verstehe mich gut mit meiner Schwester'], ['selbstbewusst', 'self-confident']],
      ex: 'Write 90 words on your family and a role model, using three tenses. Then say it aloud without notes.' },
    { id: 'de-health', n: 'Theme 1 · Healthy living & lifestyle', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Diet and exercise: Ich esse gesund / Ich treibe jeden Tag Sport, um fit zu bleiben.',
        'Unhealthy habits: rauchen, Alkohol trinken, Drogen nehmen, zu wenig schlafen, der Stress.',
        'Resolutions with the future: Ich werde mehr Obst essen. Ich sollte früher ins Bett gehen.',
        'Use um … zu (in order to) and man sollte (one should).'],
      cards: [['gesund / ungesund', 'healthy / unhealthy'], ['sich fit halten', 'to keep fit'], ['die Ernährung', 'diet / nutrition'], ['das Rauchen aufgeben', 'to give up smoking'],
        ['die Sucht', 'addiction'], ['abnehmen', 'to lose weight'], ['zunehmen', 'to gain weight'], ['der Stress', 'stress'],
        ['I do sport in order to stay fit', 'Ich treibe Sport, um fit zu bleiben'], ['You should sleep more', 'Man sollte mehr schlafen']],
      ex: 'Translate 5 English sentences about health into German, including one um … zu and one past tense.' },
    { id: 'de-school', n: 'Theme 1 · Education & work', p: ['de-ls', 'de-w', 'de-s'], w: 3, from: '2026-11-02',
      pts: ['School: Mein Lieblingsfach ist …, weil der Lehrer lustig ist. Wir müssen eine Uniform tragen.',
        'Opinions on rules and pressure: Ich finde die Schulregeln zu streng. Die Prüfungen sind stressig.',
        'Future plans: Nächstes Jahr werde ich in die Oberstufe gehen / an die Uni gehen / eine Lehre machen.',
        'Jobs: Ich möchte Arzt/Ärztin werden, weil … Ich habe ein Praktikum bei … gemacht. Job titles take no article: Ich bin Lehrer.'],
      cards: [['das Lieblingsfach', 'favourite subject'], ['die Prüfung', 'exam'], ['streng', 'strict'], ['das Praktikum', 'work experience / internship'],
        ['sich bewerben um', 'to apply for'], ['verdienen', 'to earn'], ['der Nebenjob', 'part-time job'], ['die Stelle', 'post / position'],
        ['arbeitslos', 'unemployed'], ['die Oberstufe', 'sixth form'], ['I would like to become a doctor', 'Ich möchte Arzt/Ärztin werden'], ['We have to wear a uniform', 'Wir müssen eine Uniform tragen']],
      ex: 'Answer 5 conversation questions on school and future plans aloud (record yourself), then write the best answer out.' },
    { id: 'de-free', n: 'Theme 2 · Free-time activities', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Hobbies with frequency and word order: Am Wochenende gehe ich oft mit Freunden ins Kino.',
        'Separable verbs: fernsehen → Ich sehe fern. ausgehen → Ich gehe aus.',
        'Past: Letztes Wochenende habe ich Fußball gespielt und bin ins Schwimmbad gegangen.',
        'Opinions: Das macht Spaß. Ich interessiere mich für Musik.'],
      cards: [['Sport treiben', 'to do sport'], ['die Mannschaft', 'team'], ['der Verein', 'club'], ['faulenzen', 'to laze around'],
        ['sich interessieren für', 'to be interested in'], ['Das macht Spaß', 'That\'s fun'], ['ausgehen', 'to go out'], ['Last weekend I went to the cinema', 'Letztes Wochenende bin ich ins Kino gegangen']],
      ex: 'Write a 150-word account of a great weekend (past), your usual week (present) and next weekend (future).' },
    { id: 'de-fest', n: 'Theme 2 · Customs, festivals & celebrations', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['German festivals: Weihnachten (Heiligabend on 24 December, the Adventskranz, Weihnachtsmärkte), Ostern, Silvester, Karneval/Fasching, das Oktoberfest.',
        'Describe a celebration: Wir haben Geburtstag gefeiert. Ich habe viele Geschenke bekommen.',
        'Compare traditions: In Deutschland bekommt man die Geschenke am Heiligabend, aber in England am 25. Dezember.'],
      cards: [['das Fest', 'festival / celebration'], ['feiern', 'to celebrate'], ['Heiligabend', 'Christmas Eve'], ['Silvester', 'New Year\'s Eve'],
        ['das Geschenk', 'present'], ['die Hochzeit', 'wedding'], ['der Weihnachtsmarkt', 'Christmas market'], ['We celebrated my birthday', 'Wir haben meinen Geburtstag gefeiert']],
      ex: 'Describe the photo of a festival aloud for 1 minute, then answer "Was hast du letztes Weihnachten gemacht?"' },
    { id: 'de-celeb', n: 'Theme 2 · Celebrity culture', p: ['de-ls', 'de-w', 'de-s'], w: 1,
      pts: ['Opinions on celebrities: Promis sind (keine) gute Vorbilder, weil …',
        'Influence of social media: Viele Jugendliche folgen Influencern in den sozialen Medien.',
        'Use relative clauses: Ein Star, der viel Geld verdient, sollte anderen helfen.'],
      cards: [['der Promi', 'celebrity'], ['berühmt', 'famous'], ['der Einfluss', 'influence'], ['die Sendung', 'programme / show'], ['der Schauspieler', 'actor'],
        ['A celebrity who earns a lot should help others', 'Ein Promi, der viel verdient, sollte anderen helfen']],
      ex: 'Write 90 words: "Sind Promis gute Vorbilder?" — both sides and your conclusion.' },
    { id: 'de-travel', n: 'Theme 3 · Travel & tourism', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Past holiday (perfect with sein for movement): Letzten Sommer bin ich nach Spanien gefahren/geflogen.',
        'Imperfect for descriptions: Das Wetter war sonnig. Es gab viel zu tun. Das Hotel hatte einen Pool.',
        'Future and conditional: Nächstes Jahr werde ich … Wenn ich reich wäre, würde ich nach Australien reisen.',
        'Places of interest: Sehenswürdigkeiten besichtigen, einen Ausflug machen, übernachten, die Unterkunft.'],
      cards: [['die Unterkunft', 'accommodation'], ['die Jugendherberge', 'youth hostel'], ['die Sehenswürdigkeit', 'sight / tourist attraction'], ['besichtigen', 'to visit (a sight)'],
        ['übernachten', 'to stay overnight'], ['im Ausland', 'abroad'], ['der Ausflug', 'trip / excursion'], ['es regnete', 'it was raining'],
        ['Last summer I flew to Spain', 'Letzten Sommer bin ich nach Spanien geflogen'], ['If I were rich, I would travel to Australia', 'Wenn ich reich wäre, würde ich nach Australien reisen']],
      ex: 'Speaking practice: a holiday role-play (booking a room, asking for directions) + 4 conversation questions.' },
    { id: 'de-media', n: 'Theme 3 · Media & technology', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Uses: Ich benutze mein Handy, um mit Freunden zu chatten / Musik herunterzuladen.',
        'Dangers: Cybermobbing, Datenschutz, Sucht, zu viel Zeit vor dem Bildschirm.',
        'Balanced view: Einerseits … andererseits … Meiner Meinung nach …'],
      cards: [['herunterladen', 'to download'], ['die Gefahr', 'danger'], ['das Cybermobbing', 'cyberbullying'], ['soziale Netzwerke', 'social networks'],
        ['die Werbung', 'advertising'], ['einerseits … andererseits', 'on the one hand … on the other hand'], ['I use my phone to chat with friends', 'Ich benutze mein Handy, um mit Freunden zu chatten']],
      ex: 'Translate a 50-word paragraph on technology into German (Higher translation style).' },
    { id: 'de-env', n: 'Theme 3 · Environment & where people live', p: ['de-ls', 'de-w', 'de-s'], w: 3, from: '2027-01-04',
      pts: ['Where you live: Ich wohne in einer Stadt in Ostengland. Es gibt … aber es gibt keinen/keine/kein …',
        'Pros and cons: Der Vorteil ist, dass … Der Nachteil ist, dass … (verb to the end after dass).',
        'Environment: Man sollte mehr recyceln, Energie sparen und öffentliche Verkehrsmittel benutzen.',
        'Social issues: Armut, Obdachlosigkeit. Global events and helping others: Ich würde gern freiwillig arbeiten.'],
      cards: [['die Umwelt', 'environment'], ['der Umweltschutz', 'environmental protection'], ['die Verschmutzung', 'pollution'], ['der Müll', 'rubbish'],
        ['Energie sparen', 'to save energy'], ['öffentliche Verkehrsmittel', 'public transport'], ['die Armut', 'poverty'], ['die Obdachlosigkeit', 'homelessness'],
        ['auf dem Land', 'in the countryside'], ['die Gegend', 'area / region'], ['There is no cinema', 'Es gibt kein Kino'], ['The advantage is that it is quiet', 'Der Vorteil ist, dass es ruhig ist']],
      ex: 'Write 150 words on your town and the environment: what you did, what you do and what you will do.' },
    { id: 'de-tenses', n: 'Grammar · Tenses', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Present: irregular stem changes in du/er (fahren → fährt, essen → isst, lesen → liest).',
        'Perfect: haben/sein + past participle at the end. Use sein for movement or change of state (gehen, fahren, fliegen, bleiben).',
        'Imperfect: war, hatte, es gab, and modals (konnte, musste, wollte, durfte).',
        'Future: werden + infinitive at the end. Conditional: würde + infinitive, plus wäre and hätte.',
        'Pluperfect (H): hatte/war + participle (Nachdem ich gegessen hatte, …).'],
      cards: [['Perfect of "I went"', 'Ich bin gegangen'], ['Perfect of "I ate"', 'Ich habe gegessen'], ['Imperfect of "there was"', 'es gab'], ['"I will play"', 'Ich werde spielen'],
        ['"I would travel"', 'Ich würde reisen'], ['"I had to"', 'Ich musste'], ['er (fahren)', 'er fährt'], ['"If I had time"', 'Wenn ich Zeit hätte']],
      ex: 'Conjugate 6 key verbs in 5 tenses from memory, then check.' },
    { id: 'de-wordorder', n: 'Grammar · Word order & conjunctions', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Verb second: Am Montag spiele ich … (after a time phrase, the verb comes next, then the subject).',
        'Time – Manner – Place: Ich fahre am Samstag mit dem Bus in die Stadt.',
        'Verb to the end after weil, dass, wenn, als, ob, obwohl, damit: …, weil es Spaß macht.',
        'No change after und, aber, oder, denn, sondern.',
        'Modal verbs and werden send the infinitive to the end. um … zu + infinitive at the end. Relative clauses send the verb to the end.'],
      cards: [['"On Mondays I play football"', 'Am Montag spiele ich Fußball'], ['"…because it is fun"', '…, weil es Spaß macht'], ['Order for TMP', 'Time, Manner, Place'],
        ['Which conjunctions DON\'T change word order?', 'und, aber, oder, denn, sondern'], ['"When I was young, …"', 'Als ich jung war, …']],
      ex: 'Write 8 sentences, each starting with a different time phrase or subordinate clause.' },
    { id: 'de-cases', n: 'Grammar · Cases, prepositions & adjectives', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Nominative = subject. Accusative = direct object (der → den; einen, keinen). Dative = indirect object (dem, der, dem, den + n).',
        'Accusative prepositions: durch, für, gegen, ohne, um. Dative prepositions: aus, außer, bei, mit, nach, seit, von, zu (zum, zur).',
        'Two-way prepositions (an, auf, hinter, in, neben, über, unter, vor, zwischen): accusative for movement, dative for position.',
        'Adjective endings: learn the common patterns (ein großer Hund, mit meinem besten Freund).'],
      cards: [['Accusative prepositions', 'durch, für, gegen, ohne, um'], ['Dative prepositions', 'aus, außer, bei, mit, nach, seit, von, zu'],
        ['"I go into town" (movement)', 'Ich gehe in die Stadt'], ['"I am in town" (position)', 'Ich bin in der Stadt'], ['mit + der Bus', 'mit dem Bus']],
      ex: 'Do a 20-question case/preposition quiz. For any you miss, write 2 new example sentences.' },
    { id: 'de-exam', n: 'Exam skills · Speaking, dictation & translation', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Speaking: role-play (answer every prompt and ask the question), read-aloud (practise sound–spelling), photo card (describe people, place, action, then give an opinion).',
        'Develop every conversation answer: opinion + reason + example + another tense.',
        'Dictation (Listening): write exactly what you hear. Sound rules: ei → "eye", ie → "ee", w → "v", v → "f", z → "ts", st/sp → "sht/shp".',
        'Translation into English: natural English, no missing words, correct tense. Into German (Writing): verb position, genders and cases.'],
      cards: [['How is "ie" pronounced?', 'Like English "ee" (e.g. "Liebe")'], ['How is "ei" pronounced?', 'Like English "eye" (e.g. "mein")'],
        ['Four parts of a developed speaking answer', 'Opinion + reason + example + another time frame'], ['How is German "w" pronounced?', 'Like English "v"']],
      ex: 'Do one read-aloud text and one photo card aloud, timing yourself. Then do one dictation from a sample paper.' }
  ]
});
