/* German — AQA GCSE German 8662 (new specification, first exams 2026) — Chesterton exams page + Y10/Y11 German maps */
RG.subjects.push({
  id: 'german', name: 'German', board: 'AQA', spec: '8662', quals: 1, share: 0.12,
  tierable: true,
  link: 'https://www.aqa.org.uk/subjects/german/gcse/german-8662',
  papers: [
    { id: 'de-ls', code: '8662/L + R', name: 'Listening + Reading (same session)', date: '2027-05-10', time: 'pm', dur: 105 },
    { id: 'de-w', code: '8662/W', name: 'Writing', date: '2027-05-18', time: 'pm', dur: 75 },
    { id: 'de-s', code: '8662/S', name: 'Speaking (with your teacher — date set by school, before 24 May)', date: '2027-04-26', time: '—', dur: 15, approx: true }
  ],
  structure: [
    'Four papers, 25% each. Tier (Foundation or Higher) is the same for all four.',
    'Listening: F 35 min / H 45 min, including a dictation section. Reading: F 45 min / H 1 hour, including translation into English. Both are on Monday 10 May (pm).',
    'Writing: F 1h 10m / H 1h 15m. Foundation: 5 sentences about a photo, ~50-word task, 5 grammar tasks, translation into German (35+ words), ~90-word task. Higher: translation into German (50+ words), ~90-word task, ~150-word task (choices on the longer tasks).',
    'Speaking: role-play (10 marks), reading aloud + short conversation (15), photo card + unprepared conversation (25), after 15 minutes\' supervised preparation. F 7–9 min, H 10–12 min. Conducted by the school before 24 May 2027 — the date shown here is a placeholder.',
    'Themes: 1 People & lifestyle · 2 Popular culture · 3 Communication & the world around us. Exams are based on AQA\'s prescribed vocabulary list (Appendix 2 of the spec) — the flashcards here only use words from that list.'
  ],
  technique: [
    'Vocabulary is the single biggest lever: 10–15 minutes of flashcards every day beats a weekly cram.',
    'Every writing and speaking answer should use three time frames (past, present, future), opinions with reasons (weil …), and one "wow" structure (wenn ich … wäre, würde ich …).',
    'Listening: read the questions in the reading time, predict the vocabulary, and don\'t change an answer just because a word is repeated.',
    'Dictation: know the German sound–spelling rules (ei = "eye", ie = "ee", w = "v", v = "f", sch, ch, ß, umlauts).',
    'Translation: translate every word, check verb position and tense, and don\'t leave blanks.'
  ],
  resources: [
    ['AQA 8662 spec, vocabulary list & sample papers', 'https://www.aqa.org.uk/subjects/german/gcse/german-8662'],
    ['BBC Bitesize GCSE German', 'https://www.bbc.co.uk/bitesize/levels/z98jmp3']
  ],
  topics: [
    { id: 'de-rel', n: 'Theme 1 · Identity & relationships', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Describe family and friends: Ich verstehe mich gut mit meiner Mutter, weil sie geduldig ist.',
        'Relationships and conflict: Mein Bruder geht mir auf die Nerven. Wir streiten uns oft.',
        'Role models (H): Mein Vorbild ist …, weil er/sie hilfsbereit und ehrlich ist.',
        'Future: Ich möchte (nicht) heiraten / Kinder haben, weil …',
        'Every word on these cards is on AQA\'s official 8662 vocabulary list. (H) = Higher tier only.'],
      cards: [['sich verstehen mit (+ dative)', 'to get on with'], ['jdm auf die Nerven gehen', 'to get on someone\'s nerves'], ['das Vorbild (H)', 'role model'],
        ['geduldig', 'patient'], ['hilfsbereit', 'helpful'], ['eifersüchtig (H)', 'jealous'], ['geschieden', 'divorced'], ['ledig', 'single (unmarried)'],
        ['der Stiefvater (Stief- = step-)', 'stepfather'], ['streiten', 'to argue'], ['die Beziehung', 'relationship'], ['vertrauen (H)', 'to trust'],
        ['I get on well with my sister', 'Ich verstehe mich gut mit meiner Schwester']],
      ex: 'Write 90 words on your family and a role model, using three tenses. Then say it aloud without notes.' },
    { id: 'de-health', n: 'Theme 1 · Healthy living & lifestyle', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Diet and exercise: Ich esse gesund. Ich treibe jeden Tag Sport, um gesund zu bleiben.',
        'Unhealthy habits: rauchen, Alkohol trinken, Drogen nehmen, zu wenig schlafen.',
        'Resolutions with the future: Ich werde mehr Gemüse essen. Man sollte früher ins Bett gehen.',
        'Use um … zu (in order to) and man sollte (one should).'],
      cards: [['gesund', 'healthy'], ['die Gesundheit', 'health'], ['die Ernährung (H)', 'diet / nutrition'], ['rauchen', 'to smoke'], ['die Zigarette', 'cigarette'],
        ['aufgeben (H)', 'to give up'], ['abnehmen', 'to lose weight'], ['zunehmen', 'to gain weight'], ['die Droge', 'drug'], ['krank', 'ill'], ['die Krankheit', 'illness'],
        ['I do sport in order to stay healthy', 'Ich treibe Sport, um gesund zu bleiben'], ['You should sleep more', 'Man sollte mehr schlafen']],
      ex: 'Translate 5 English sentences about health into German, including one um … zu and one past tense.' },
    { id: 'de-school', n: 'Theme 1 · Education & work', p: ['de-ls', 'de-w', 'de-s'], w: 3, from: '2026-11-02',
      pts: ['School: Mein Lieblingsfach ist …, weil der Lehrer lustig ist. Wir müssen eine Uniform tragen.',
        'Opinions on rules and pressure: Die Regeln sind zu streng. Die Prüfungen (H) sind schwierig.',
        'Future plans: Nächstes Jahr werde ich in die Oberstufe (H) gehen / an die Universität gehen / eine Lehre (H) machen.',
        'Jobs: Ich möchte Arzt/Ärztin werden, weil … Ich möchte bei einer großen Firma arbeiten. Job titles take no article: Ich bin Lehrer.'],
      cards: [['Lieblings- (+ noun)', 'favourite … (e.g. das Lieblingsfach)'], ['die Prüfung (H)', 'exam'], ['streng', 'strict'], ['verdienen', 'to earn'],
        ['die Stelle', 'post / position'], ['arbeitslos', 'unemployed'], ['die Oberstufe (H)', 'sixth form'], ['die Lehre (H)', 'apprenticeship'], ['der Beruf', 'job / profession'],
        ['die Erfahrung', 'experience'], ['die Firma', 'company'], ['der Kollege', 'colleague'],
        ['I would like to become a doctor', 'Ich möchte Arzt/Ärztin werden'], ['We have to wear a uniform', 'Wir müssen eine Uniform tragen']],
      ex: 'Answer 5 conversation questions on school and future plans aloud (record yourself), then write the best answer out.' },
    { id: 'de-free', n: 'Theme 2 · Free-time activities', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Hobbies with frequency and word order: Am Wochenende gehe ich oft mit Freunden ins Kino.',
        'Separable verbs: fernsehen → Ich sehe fern. ausgehen → Ich gehe aus.',
        'Past: Letztes Wochenende habe ich Fußball gespielt und bin schwimmen gegangen.',
        'Opinions: Das macht Spaß. Ich interessiere mich für Musik.'],
      cards: [['Sport treiben', 'to do sport'], ['die Mannschaft', 'team'], ['der Verein', 'club'], ['die Freizeit', 'free time'],
        ['sich interessieren für', 'to be interested in'], ['Das macht Spaß', 'That\'s fun'], ['ausgehen', 'to go out'], ['fernsehen', 'to watch TV'], ['das Konzert', 'concert'],
        ['Last weekend I went to the cinema', 'Letztes Wochenende bin ich ins Kino gegangen']],
      ex: 'Write a 150-word account of a great weekend (past), your usual week (present) and next weekend (future).' },
    { id: 'de-fest', n: 'Theme 2 · Customs, festivals & celebrations', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['German festivals: Weihnachten (presents on Heiliger Abend, 24 December), Ostern, Silvester, Karneval (H).',
        'Describe a celebration: Wir haben Geburtstag gefeiert. Ich habe viele Geschenke bekommen.',
        'Compare traditions: In Deutschland bekommt man die Geschenke am Heiligen Abend, aber in England am 25. Dezember.'],
      cards: [['das Fest', 'festival / celebration'], ['die Feier', 'party / celebration'], ['feiern', 'to celebrate'], ['der Heilige Abend', 'Christmas Eve'], ['Silvester', 'New Year\'s Eve'],
        ['das Geschenk', 'present'], ['die Hochzeit', 'wedding'], ['die Tradition', 'tradition'], ['der Karneval (H)', 'carnival'],
        ['We celebrated my birthday', 'Wir haben meinen Geburtstag gefeiert']],
      ex: 'Describe a photo of a festival aloud for 1 minute, then answer "Was hast du letztes Weihnachten gemacht?"' },
    { id: 'de-celeb', n: 'Theme 2 · Celebrity culture', p: ['de-ls', 'de-w', 'de-s'], w: 1,
      pts: ['Opinions on celebrities: Stars sind gute Vorbilder (H) / keine guten Vorbilder, weil …',
        'Influence (H) of the media: Viele junge Leute folgen Stars in den sozialen Medien.',
        'Use relative clauses: Ein Star, der viel Geld verdient, sollte anderen helfen.'],
      cards: [['berühmt', 'famous'], ['der Star', 'star / celebrity'], ['der Einfluss (H)', 'influence'], ['die Sendung', 'programme / show'], ['der Schauspieler', 'actor'],
        ['der Sänger', 'singer'], ['der Fan (H)', 'fan'], ['die sozialen Medien', 'social media'],
        ['A star who earns a lot should help others', 'Ein Star, der viel verdient, sollte anderen helfen']],
      ex: 'Write 90 words: "Sind Stars gute Vorbilder?" — both sides and your conclusion.' },
    { id: 'de-travel', n: 'Theme 3 · Travel & tourism', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Past holiday (perfect with sein for movement): Letzten Sommer bin ich nach Spanien geflogen.',
        'Imperfect for descriptions: Das Wetter war sonnig. Es gab viel zu tun. Das Hotel hatte einen Pool.',
        'Future and conditional: Nächstes Jahr werde ich … Wenn ich reich wäre, würde ich nach Australien reisen.',
        'Places of interest: ein Schloss / ein Museum besuchen, einen Ausflug (H) machen, am Strand liegen.'],
      cards: [['der Urlaub', 'holiday'], ['die Ferien', 'holidays (school)'], ['das Ausland (H)', 'abroad (im Ausland)'], ['der Ausflug (H)', 'trip / excursion'],
        ['das Hotel', 'hotel'], ['das Zelt (H)', 'tent'], ['das Schloss', 'castle'], ['das Museum', 'museum'], ['besuchen', 'to visit'], ['der Strand', 'beach'],
        ['Last summer I flew to Spain', 'Letzten Sommer bin ich nach Spanien geflogen'], ['If I were rich, I would travel to Australia', 'Wenn ich reich wäre, würde ich nach Australien reisen']],
      ex: 'Speaking practice: a holiday role-play (booking a room, asking for directions) + 4 conversation questions.' },
    { id: 'de-media', n: 'Theme 3 · Media & technology', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Uses: Ich benutze mein Handy, um Nachrichten zu schicken und Musik herunterzuladen.',
        'Dangers: Mobbing, zu viel Zeit online, Gefahren im Internet.',
        'Balanced view: Ein Vorteil ist, dass … Ein Nachteil ist, dass … Meiner Meinung nach …'],
      cards: [['herunterladen', 'to download'], ['die Gefahr', 'danger'], ['das Mobbing', 'bullying'], ['die sozialen Medien', 'social media'], ['die Werbung (H)', 'advertising'],
        ['das Gerät (H)', 'device'], ['die Nachricht', 'message / news'], ['benutzen', 'to use'], ['der Vorteil / der Nachteil', 'advantage / disadvantage'],
        ['I use my phone to send messages', 'Ich benutze mein Handy, um Nachrichten zu schicken']],
      ex: 'Translate a 50-word paragraph on technology into German (Higher translation style).' },
    { id: 'de-env', n: 'Theme 3 · Environment & where people live', p: ['de-ls', 'de-w', 'de-s'], w: 3, from: '2027-01-04',
      pts: ['Where you live: Ich wohne in einer Stadt in England. Es gibt … aber es gibt keinen/keine/kein …',
        'Pros and cons: Der Vorteil ist, dass … Der Nachteil ist, dass … (verb to the end after dass).',
        'Environment: Man sollte mehr recyceln, Energie sparen und mit dem Bus fahren, um die Umwelt zu schützen.',
        'Helping others: Ich würde gern freiwillig arbeiten, um armen (H) Leuten zu helfen.'],
      cards: [['die Umwelt', 'environment'], ['die Umwelt schützen', 'to protect the environment'], ['verschmutzen', 'to pollute'], ['der Müll', 'rubbish'], ['recyceln', 'to recycle'],
        ['Energie sparen', 'to save energy'], ['der Klimawandel (H)', 'climate change'], ['der Verkehr', 'traffic'], ['arm (H)', 'poor'], ['freiwillig', 'voluntary / voluntarily'],
        ['auf dem Land', 'in the countryside'], ['die Gegend', 'area / region'], ['das Dorf', 'village'], ['There is no cinema', 'Es gibt kein Kino'],
        ['The advantage is that it is quiet', 'Der Vorteil ist, dass es ruhig ist']],
      ex: 'Write 150 words on your town and the environment: what you did, what you do and what you will do.' },
    { id: 'de-tenses', n: 'Grammar · Tenses', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Present: irregular stem changes in du/er (fahren → fährt, essen → isst, lesen → liest).',
        'Perfect: haben/sein + past participle at the end. Use sein for movement or change of state (gehen, fahren, fliegen, bleiben).',
        'Imperfect: war, hatte, es gab, and modals (konnte, musste, wollte, durfte).',
        'Future: werden + infinitive at the end. Conditional: würde + infinitive, plus wäre and hätte.',
        'Pluperfect (H): hatte/war + participle (Nachdem ich gegessen hatte, …).'],
      cards: [['Perfect of "I went"', 'Ich bin gegangen'], ['Perfect of "I ate"', 'Ich habe gegessen'], ['Imperfect of "there was"', 'es gab'], ['"I will play"', 'Ich werde spielen'],
        ['"I would travel"', 'Ich würde reisen'], ['"I had to"', 'Ich musste'], ['er (fahren)', 'er fährt'], ['"If I had time"', 'Wenn ich Zeit hätte']],
      ex: 'Conjugate 6 key verbs in 5 tenses from memory, then check.' },
    { id: 'de-wordorder', n: 'Grammar · Word order & conjunctions', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Verb second: Am Montag spiele ich … (after a time phrase, the verb comes next, then the subject).',
        'Time – Manner – Place: Ich fahre am Samstag mit dem Bus in die Stadt.',
        'Verb to the end after weil, dass, wenn, als, ob, obwohl, damit: …, weil es Spaß macht.',
        'No change after und, aber, oder, denn, sondern.',
        'Modal verbs and werden send the infinitive to the end. um … zu + infinitive at the end. Relative clauses send the verb to the end.'],
      cards: [['"On Mondays I play football"', 'Am Montag spiele ich Fußball'], ['"…because it is fun"', '…, weil es Spaß macht'], ['Order for TMP', 'Time, Manner, Place'],
        ['Which conjunctions DON\'T change word order?', 'und, aber, oder, denn, sondern'], ['"When I was young, …"', 'Als ich jung war, …']],
      ex: 'Write 8 sentences, each starting with a different time phrase or subordinate clause.' },
    { id: 'de-cases', n: 'Grammar · Cases, prepositions & adjectives', p: ['de-ls', 'de-w', 'de-s'], w: 2,
      pts: ['Nominative = subject. Accusative = direct object (der → den; einen, keinen). Dative = indirect object (dem, der, dem, den + n).',
        'Accusative prepositions: durch, für, gegen, ohne, um. Dative prepositions: aus, außer, bei, mit, nach, seit, von, zu (zum, zur).',
        'Two-way prepositions (an, auf, hinter, in, neben, über, unter, vor, zwischen): accusative for movement, dative for position.',
        'Adjective endings: learn the common patterns (ein großer Hund, mit meinem besten Freund).'],
      cards: [['Accusative prepositions', 'durch, für, gegen, ohne, um'], ['Dative prepositions', 'aus, außer, bei, mit, nach, seit, von, zu'],
        ['"I go into town" (movement)', 'Ich gehe in die Stadt'], ['"I am in town" (position)', 'Ich bin in der Stadt'], ['mit + der Bus', 'mit dem Bus']],
      ex: 'Do a 20-question case/preposition quiz. For any you miss, write 2 new example sentences.' },
    { id: 'de-exam', n: 'Exam skills · Speaking, dictation & translation', p: ['de-ls', 'de-w', 'de-s'], w: 3,
      pts: ['Speaking: role-play (answer every prompt and ask the question), read-aloud (practise sound–spelling), photo card (describe people, place, action, then give an opinion).',
        'Develop every conversation answer: opinion + reason + example + another tense.',
        'Dictation (Listening): write exactly what you hear. Sound rules: ei → "eye", ie → "ee", w → "v", v → "f", z → "ts", st/sp → "sht/shp".',
        'Translation into English: natural English, no missing words, correct tense. Into German (Writing): verb position, genders and cases.'],
      cards: [['How is "ie" pronounced?', 'Like English "ee" (e.g. "Liebe")'], ['How is "ei" pronounced?', 'Like English "eye" (e.g. "mein")'],
        ['Four parts of a developed speaking answer', 'Opinion + reason + example + another time frame'], ['How is German "w" pronounced?', 'Like English "v"']],
      ex: 'Do one read-aloud text and one photo card aloud, timing yourself. Then do one dictation from a sample paper.' }
  ]
});
