/* Maths — Pearson Edexcel GCSE Mathematics 1MA1 (Chesterton exams page) */
RG.subjects.push({
  id: 'maths', name: 'Maths', board: 'Edexcel', spec: '1MA1', quals: 1, share: 0.20,
  tierable: true,
  link: 'https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.html',
  papers: [
    { id: 'm1', code: '1MA1/1', name: 'Paper 1 · Non-calculator', date: '2027-05-14', time: 'am', dur: 90 },
    { id: 'm2', code: '1MA1/2', name: 'Paper 2 · Calculator', date: '2027-05-27', time: 'am', dur: 90 },
    { id: 'm3', code: '1MA1/3', name: 'Paper 3 · Calculator', date: '2027-06-14', time: 'am', dur: 90 }
  ],
  structure: [
    'Three papers, 1h 30m each, 80 marks each, equal weighting. Paper 1 has no calculator.',
    'Foundation (grades 1–5) or Higher (grades 4–9) — set your tier in Settings.',
    'Any topic can come up on any paper, so every topic is revised for all three.'
  ],
  technique: [
    'About 1 mark per minute. Circle the marks for each question and budget time.',
    'Always show working: most marks are method marks, even when the final answer is wrong.',
    'Underline the instruction: units, decimal places, "give reasons", "show that".',
    'Check your calculator is in Degrees (D) before any trig question.',
    'You get a formula sheet in every paper (trapezium, prism, circles, Pythagoras, trig ratios, compound interest, probability; Higher also the quadratic formula, sine/cosine rules and ½ab sin C). You still need exact trig values, speed/density/pressure, arc and sector, y = mx + c — see "Formula sheet" topic.',
    'Non-calc: practise written multiplication, division and fraction arithmetic until automatic.',
    'Stuck? Write down anything you know (a formula, a labelled diagram). Then move on and come back.'
  ],
  resources: [
    ['Corbettmaths 5-a-day (daily practice)', 'https://corbettmaths.com/5-a-day/gcse/'],
    ['Physics & Maths Tutor (questions by topic)', 'https://www.physicsandmathstutor.com/'],
    ['Edexcel 1MA1 specification & past papers', 'https://qualifications.pearson.com/en/qualifications/edexcel-gcses/mathematics-2015.html']
  ],
  topics: [
    { id: 'm-num', n: 'Primes, HCF, LCM & index laws', w: 3,
      pts: ['Product of prime factors: factor tree, then write with powers — 360 = 2³ × 3² × 5.',
        'HCF = multiply the primes they share (lowest powers). LCM = every prime, highest powers. A Venn diagram helps.',
        'Index laws: aᵐ × aⁿ = aᵐ⁺ⁿ, aᵐ ÷ aⁿ = aᵐ⁻ⁿ, (aᵐ)ⁿ = aᵐⁿ, a⁰ = 1.',
        'Negative index = reciprocal: a⁻ⁿ = 1/aⁿ. Fractional index = root: a^(1/n) = ⁿ√a, a^(m/n) = (ⁿ√a)ᵐ.'],
      cards: [['Write 84 as a product of prime factors', '2² × 3 × 7'], ['HCF and LCM of 24 and 36', 'HCF 12, LCM 72'],
        ['Evaluate 8^(2/3)', '(∛8)² = 2² = 4'], ['Evaluate 27^(−1/3)', '1/3'], ['Simplify (x³)⁴ ÷ x⁵', 'x⁷']],
      ex: 'Do 6 mixed questions: two HCF/LCM word problems (e.g. buses leaving together) and four index-law questions including fractional and negative powers.' },
    { id: 'm-frac', n: 'Fractions, percentages & interest', w: 3,
      pts: ['Add/subtract fractions: common denominator. Multiply: tops × tops, bottoms × bottoms. Divide: flip the second and multiply.',
        'Convert mixed numbers to improper fractions before multiplying or dividing.',
        'Multipliers: +15% → × 1.15, −15% → × 0.85. Percentage change = change ÷ original × 100.',
        'Reverse percentage: divide by the multiplier (after a 20% rise, £66 ÷ 1.2 = £55 originally).',
        'Compound interest / growth: amount = P × (multiplier)ⁿ (the compound interest formula is on the formula sheet). Depreciation uses a multiplier below 1.',
        'Recurring decimal → fraction (H): x = 0.4545…, 100x = 45.4545…, subtract: 99x = 45, x = 5/11.'],
      cards: [['Multiplier for a 15% decrease', '0.85'], ['£200 at 3% compound interest for 4 years', '200 × 1.03⁴ = £225.10'],
        ['Price after 20% off is £48. Original price?', '£48 ÷ 0.8 = £60'], ['2⅓ ÷ 1¾', '7/3 × 4/7 = 4/3 = 1⅓'], ['0.4̇5̇ as a fraction', '45/99 = 5/11']],
      ex: 'Non-calculator set: 3 fraction-arithmetic questions, 2 reverse-percentage questions, 1 compound-interest question (calculator).' },
    { id: 'm-bounds', n: 'Rounding, bounds & standard form', w: 2,
      pts: ['Estimate by rounding every number to 1 significant figure first.',
        'Error interval: half a unit either side — 7.3 to 1 d.p. means 7.25 ≤ x < 7.35.',
        'Upper bound of a ÷ b = UB of a ÷ LB of b. Upper bound of a − b = UB a − LB b.',
        'Standard form: A × 10ⁿ with 1 ≤ A < 10. Multiply: multiply the A parts, add the powers, then re-adjust.'],
      cards: [['0.00045 in standard form', '4.5 × 10⁻⁴'], ['(3 × 10⁴) × (4 × 10⁵)', '1.2 × 10¹⁰'],
        ['Error interval for 7.3 (1 d.p.)', '7.25 ≤ x < 7.35'], ['Upper bound of a ÷ b uses…', 'upper bound of a ÷ lower bound of b']],
      ex: 'Do 4 standard-form calculations without a calculator and 2 bounds problems (H: speed = distance ÷ time with bounds).' },
    { id: 'm-surds', n: 'Surds', w: 1, h: 1,
      pts: ['√(ab) = √a × √b. Simplify by finding a square factor: √72 = √36 × √2 = 6√2.',
        'Rationalise: multiply top and bottom by the surd — 1/√3 = √3/3.',
        'For a/(b + √c) multiply top and bottom by the conjugate (b − √c).',
        '(a + √b)(a − √b) = a² − b — a difference of two squares.'],
      cards: [['Simplify √50', '5√2'], ['Rationalise 6/√2', '3√2'], ['(3 + √2)(3 − √2)', '7'], ['√12 + √27', '2√3 + 3√3 = 5√3']],
      ex: 'Do 5 surd questions including one "rationalise with a conjugate" question.' },
    { id: 'm-alg', n: 'Expanding, factorising & algebraic fractions', w: 3,
      pts: ['Double brackets: every term times every term (grid or FOIL). Triple brackets (H): expand two, then the third.',
        'Factorise: take out the HCF first. Quadratic x² + bx + c: find a pair multiplying to c and adding to b.',
        'Difference of two squares: a² − b² = (a + b)(a − b).',
        'ax² + bx + c (H): find two numbers multiplying to ac and adding to b, split the middle term, factorise in pairs.',
        'Algebraic fractions (H): factorise everything first, then cancel common brackets.'],
      cards: [['Factorise x² + 5x + 6', '(x + 2)(x + 3)'], ['Factorise x² − 49', '(x + 7)(x − 7)'],
        ['Expand (2x − 3)(x + 4)', '2x² + 5x − 12'], ['Factorise 2x² + 7x + 3', '(2x + 1)(x + 3)'], ['Simplify (x² − 9)/(x² + 5x + 6)', '(x − 3)/(x + 2)']],
      ex: 'Do 8 factorising questions of increasing difficulty and 2 algebraic-fraction simplifications.' },
    { id: 'm-eq', n: 'Equations, inequalities & rearranging', w: 3,
      pts: ['Do the same to both sides. Collect x terms on the side with more x.',
        'Inequalities: solve like equations, but flip the sign when multiplying or dividing by a negative.',
        'Number lines: open circle for < or >, filled circle for ≤ or ≥. List integers carefully at the ends.',
        'Changing the subject: undo operations in reverse order. If the subject appears twice (H), collect terms and factorise it out.'],
      cards: [['Solve 5x − 7 = 2x + 11', 'x = 6'], ['Solve 3 − 2x > 9', 'x < −3'], ['Integers n with −3 < 2n ≤ 6', '−1, 0, 1, 2, 3'],
        ['Make t the subject: a(t + 1) = 3t + b', 't = (b − a)/(a − 3)']],
      ex: 'Do 4 equations with brackets/fractions, 2 inequalities with number lines, 2 change-the-subject questions.' },
    { id: 'm-quad', n: 'Quadratic equations & completing the square', w: 2,
      pts: ['Solve by factorising: set each bracket equal to zero.',
        'Quadratic formula: x = (−b ± √(b² − 4ac)) ÷ 2a (on the Higher formula sheet) — use it when the answer needs decimal places.',
        'Completing the square (H): x² + bx + c = (x + b/2)² − (b/2)² + c.',
        'Turning point of y = (x + p)² + q is (−p, q). The roots are where the graph crosses the x-axis.',
        'Quadratic inequalities (H): solve = 0, sketch the curve, then read off where it is above (> 0) or below (< 0) the x-axis. x² < 9 → −3 < x < 3.'],
      cards: [['Solve x² − x − 12 = 0', 'x = 4 or x = −3'], ['Complete the square: x² + 6x + 2', '(x + 3)² − 7'],
        ['Turning point of y = (x − 2)² + 5', '(2, 5)'], ['Solve 2x² + 3x − 4 = 0 to 2 d.p.', 'x = 0.85 or x = −2.35']],
      ex: 'Do 3 by factorising, 2 with the formula, 2 completing the square (H) — one asking for the turning point.' },
    { id: 'm-simul', n: 'Simultaneous equations', w: 2,
      pts: ['Elimination: make one coefficient match, then add (different signs) or subtract (same signs).',
        'Substitute your first answer back into an original equation to find the second unknown.',
        'Linear + quadratic (H): rearrange the linear one, substitute into the quadratic, solve, and pair up the answers.',
        'Graphically, solutions are the intersection points.'],
      cards: [['2x + y = 7 and x − y = 2', 'x = 3, y = 1'], ['3x + 2y = 16 and x + 2y = 8', 'x = 4, y = 2'],
        ['y = x + 1 and x² + y² = 13', '(2, 3) and (−3, −2)']],
      ex: 'Do 3 linear pairs (one set in a word problem, e.g. prices of tickets) and 1 linear–quadratic pair (H).' },
    { id: 'm-seq', n: 'Sequences & nth term', w: 2,
      pts: ['Linear nth term: (difference) × n + (first term − difference). 5, 8, 11… → 3n + 2.',
        'Is a number in the sequence? Set nth term = number and check whether n is a whole number.',
        'Quadratic nth term (H): half the second difference = coefficient of n². Subtract that n² part and find the linear rest.',
        'Geometric sequences multiply by a common ratio. Fibonacci-type: add the previous two terms.'],
      cards: [['nth term of 7, 11, 15, 19', '4n + 3'], ['nth term of 20, 17, 14', '23 − 3n'], ['Is 100 in 3n + 2?', 'No — 3n = 98 gives n that is not whole'],
        ['nth term of 2, 6, 12, 20, 30', 'n² + n']],
      ex: 'Do 3 linear nth-term questions and 2 quadratic nth-term questions (H).' },
    { id: 'm-lines', n: 'Straight-line graphs & coordinates', w: 2,
      pts: ['y = mx + c: m is the gradient, c is the y-intercept.',
        'Gradient = change in y ÷ change in x between two points.',
        'Parallel lines have equal gradients. Perpendicular gradients multiply to −1 (H).',
        'Midpoint = average of the x-values and average of the y-values. Distance: Pythagoras on the differences.'],
      cards: [['Gradient through (1, 3) and (4, 12)', '3'], ['Line through (2, 5) with gradient 3', 'y = 3x − 1'],
        ['Gradient perpendicular to y = 2x + 1', '−½'], ['Midpoint of (2, 4) and (8, 10)', '(5, 7)']],
      ex: 'Do 4 questions: find an equation from two points, a parallel line, a perpendicular line (H), and a midpoint problem.' },
    { id: 'm-graphs', n: 'Curved graphs, functions & transformations', w: 2,
      pts: ['Know the shapes: quadratic (U or ∩), cubic, reciprocal y = 1/x (never touches the axes), exponential y = kˣ.',
        'Circle x² + y² = r² has centre (0, 0) (H). A tangent is perpendicular to the radius.',
        'Composite fg(x) = f(g(x)) — do g first. Inverse f⁻¹(x): write y = f(x), swap x and y, rearrange (H).',
        'Transformations (H): f(x) + a moves up a; f(x + a) moves LEFT a; −f(x) reflects in the x-axis; f(−x) reflects in the y-axis.',
        'Real-life graphs: gradient = rate (speed, acceleration). Area under a velocity–time graph = distance.'],
      cards: [['f(x) = 2x + 1, g(x) = x². Find fg(3).', 'f(9) = 19'], ['Inverse of f(x) = 3x − 4', 'f⁻¹(x) = (x + 4)/3'],
        ['What does y = f(x − 2) do?', 'Translates right by 2'], ['Radius of x² + y² = 49', '7'], ['Gradient of a velocity–time graph', 'Acceleration']],
      ex: 'Do one graph-sketching question, one functions question, and one area-under-a-graph (trapezium estimate, H) question.' },
    { id: 'm-ratio', n: 'Ratio & proportion', w: 3,
      pts: ['Sharing in a ratio: total the parts, find one part, multiply.',
        'Combine ratios by matching the shared term: a:b = 3:4 and b:c = 2:5 → 3:4:10.',
        'Best buy: compare the price per unit (or amount per £).',
        'Direct proportion y = kx. Inverse proportion y = k/x. Find k from the given pair, then use it. Also y ∝ x², y ∝ √x.'],
      cards: [['Share £60 in the ratio 2:3', '£24 and £36'], ['y ∝ x. y = 12 when x = 3. Find y when x = 5.', 'k = 4, so y = 20'],
        ['y ∝ 1/x. y = 6 when x = 2. Find y when x = 4.', 'k = 12, so y = 3'], ['a:b = 3:4 and b:c = 2:5. Find a:b:c.', '3:4:10']],
      ex: 'Do 5 ratio problems. Ratio questions are among the most common on the papers, so include "the difference between shares is…" types.' },
    { id: 'm-rates', n: 'Compound measures & units', w: 2,
      pts: ['Speed = distance ÷ time. Density = mass ÷ volume. Pressure = force ÷ area.',
        'Convert time carefully: 45 minutes = 0.75 hours, not 0.45.',
        'km/h ÷ 3.6 = m/s. Area units square the factor (1 m² = 10 000 cm²). Volume units cube it (1 m³ = 1 000 000 cm³).'],
      cards: [['60 km in 45 minutes — speed in km/h?', '80 km/h'], ['Density 8 g/cm³, volume 5 cm³ — mass?', '40 g'],
        ['18 km/h in m/s', '5 m/s'], ['200 N on 4 m² — pressure?', '50 N/m² (Pa)']],
      ex: 'Do 4 compound-measure problems, including one that combines two densities (alloy/mixture question).' },
    { id: 'm-angles', n: 'Angles, polygons & bearings', w: 2,
      pts: ['Straight line 180°, around a point 360°, triangle 180°, quadrilateral 360°.',
        'Parallel lines: alternate angles equal, corresponding angles equal, co-interior angles add to 180°.',
        'Exterior angles of any polygon add to 360°. Interior sum = (n − 2) × 180°. Regular polygon exterior = 360 ÷ n.',
        'Give the geometric reason for every step — reasons carry marks.',
        'Bearings: from north, clockwise, three figures. Back bearing = bearing ± 180°.'],
      cards: [['Interior angle sum of a hexagon', '720°'], ['Exterior angle of a regular decagon', '36°'],
        ['Regular polygon with exterior angle 24° has how many sides?', '15'], ['Bearing of A from B is 070°. Bearing of B from A?', '250°']],
      ex: 'Do 3 multi-step angle problems writing a reason for every step, plus 1 bearings question.' },
    { id: 'm-area', n: 'Area, volume & circles', w: 2,
      pts: ['Triangle ½bh. Trapezium ½(a + b)h. Circle area πr², circumference πd.',
        'Arc length = θ/360 × 2πr. Sector area = θ/360 × πr².',
        'Prism volume = cross-section area × length. Cylinder πr²h.',
        'On the 2027 formula sheet: area of a trapezium, volume of a prism, circle circumference and area. Cone and sphere formulae are printed in the question. NOT given: arc length, sector area, triangle ½bh, parallelogram — learn those.',
        '"In terms of π" means leave π in the answer.'],
      cards: [['Area of a circle, radius 5 (in terms of π)', '25π'], ['Trapezium a = 6, b = 10, h = 4', '32'],
        ['Cylinder volume, r = 3, h = 10 (in terms of π)', '90π'], ['Arc length: r = 6, angle 60°', '2π']],
      ex: 'Do 2 compound-shape area problems, 1 sector problem and 1 volume problem (H: frustum or a hemisphere on a cone).' },
    { id: 'm-trig', n: 'Pythagoras & trigonometry', w: 3,
      pts: ['a² + b² = c², where c is the hypotenuse (opposite the right angle).',
        'SOH CAH TOA: label O, A, H from the angle, choose the ratio, use inverse (sin⁻¹) to find an angle.',
        'Exact values: sin30 = cos60 = ½, sin60 = cos30 = √3/2, tan45 = 1, tan30 = 1/√3, tan60 = √3.',
        'H: sine rule a/sinA = b/sinB. Cosine rule a² = b² + c² − 2bc cosA. Area = ½ab sinC. (All three, plus Pythagoras and SOHCAHTOA, are on the formula sheet — the exact values are not.)',
        'H: 3D problems — find a 2D right-angled triangle inside the shape.',
        'H: trig graphs — y = sin x and y = cos x repeat every 360° between −1 and 1; y = tan x repeats every 180° with asymptotes at 90°, 270°.'],
      cards: [['Hypotenuse when the other sides are 5 and 12', '13'], ['sin 30°', '½'], ['tan 60°', '√3'],
        ['Area: a = 8, b = 5, C = 30°', '½ × 8 × 5 × ½ = 10'], ['When do you use the cosine rule?', 'Three sides known, or two sides and the included angle']],
      ex: 'Do 2 Pythagoras, 3 SOHCAHTOA (one non-calc exact value), and 2 sine/cosine rule questions (H).' },
    { id: 'm-transf', n: 'Transformations, congruence & similarity', w: 2,
      pts: ['Describe fully: rotation (angle, direction, centre), reflection (line equation), translation (column vector), enlargement (scale factor, centre).',
        'Negative scale factor enlarges through the centre, on the other side (H).',
        'Congruent triangles: SSS, SAS, ASA/AAS, RHS.',
        'Similar shapes: lengths × k, areas × k², volumes × k³.',
        'Constructions and loci: perpendicular bisector, angle bisector — leave your compass arcs showing.'],
      cards: [['The four congruence conditions', 'SSS, SAS, ASA (or AAS), RHS'], ['Length scale factor 3 → area scale factor?', '9'],
        ['Volumes in ratio 8:27 → lengths?', '2:3'], ['A full rotation description needs…', 'angle, direction and centre']],
      ex: 'Do 1 describe-the-transformation question, 1 congruence proof (H), 1 similar-volumes question, 1 construction.' },
    { id: 'm-circle', n: 'Circle theorems', w: 1, h: 1,
      pts: ['Angle at the centre is twice the angle at the circumference.',
        'Angles in the same segment are equal. Angle in a semicircle is 90°.',
        'Opposite angles of a cyclic quadrilateral add to 180°.',
        'Tangent meets radius at 90°. Two tangents from one point are equal in length.',
        'Alternate segment theorem: the angle between tangent and chord equals the angle in the alternate segment.',
        'The perpendicular from the centre to a chord bisects the chord.'],
      cards: [['Angle in a semicircle', '90°'], ['Opposite angles of a cyclic quadrilateral', 'Add to 180°'],
        ['Angle between a tangent and a radius', '90°'], ['Alternate segment theorem', 'Tangent–chord angle = angle in the alternate segment']],
      ex: 'Do 3 circle-theorem questions and state each theorem in full words — examiners want the wording.' },
    { id: 'm-vectors', n: 'Vectors', w: 1, h: 1,
      pts: ['AB = b − a (from A to B: go back along a, then along b).',
        'Midpoint M of AB: OM = ½(a + b). A ratio point splits AB in that ratio.',
        'Parallel vectors are multiples of each other.',
        'Collinear proof: show AB = k × BC AND that they share point B.'],
      cards: [['OA = a, OB = b. Find AB.', 'b − a'], ['M is the midpoint of AB. Find OM.', '½(a + b)'], ['How do you prove three points are collinear?', 'Show the vectors are multiples and share a point']],
      ex: 'Do 2 vector proofs from past papers (these are usually the last questions on Higher papers).' },
    { id: 'm-prob', n: 'Probability', w: 2,
      pts: ['Probabilities add to 1. P(not A) = 1 − P(A). Expected frequency = P × number of trials.',
        'Tree diagrams: multiply along branches, add between outcomes.',
        'Without replacement: the numerator and denominator both change on the second pick.',
        'Venn notation: A ∪ B = A or B, A ∩ B = A and B, A′ = not A. Conditional (H): P(A|B) = P(A ∩ B) ÷ P(B).',
        'Product rule for counting: m ways then n ways gives m × n.'],
      cards: [['P(rain) = 0.3. P(no rain)?', '0.7'], ['3 red and 2 blue. Pick 2 without replacement. P(both red)?', '3/5 × 2/4 = 3/10'],
        ['What does A ∩ B mean?', 'A and B'], ['Expected sixes in 120 rolls of a fair die', '20']],
      ex: 'Do 1 tree diagram without replacement, 1 Venn diagram question, and 1 conditional-probability question (H).' },
    { id: 'm-stats', n: 'Statistics & charts', w: 2,
      pts: ['Mean from a frequency table = Σfx ÷ Σf. Grouped data: use midpoints to get an ESTIMATE.',
        'Cumulative frequency: plot at the upper class bound. Median at n/2. IQR = UQ − LQ. Box plots (H).',
        'Histograms (H): frequency density = frequency ÷ class width. Area = frequency.',
        'Scatter graphs: describe the correlation. Interpolation is reliable; extrapolation is not.',
        'Comparing distributions: compare an average AND a spread, in context.'],
      cards: [['Frequency density', 'Frequency ÷ class width'], ['Interquartile range', 'Upper quartile − lower quartile'],
        ['Mean of 4, 8, 9, 11', '8'], ['To compare two distributions, you need…', 'An average and a measure of spread, both in context']],
      ex: 'Do 1 grouped-mean estimate, 1 cumulative-frequency/box-plot question, and 1 histogram question (H).' },
    { id: 'm-proof', n: 'Algebraic proof & iteration', w: 1, h: 1,
      pts: ['Even: 2n. Odd: 2n + 1. Consecutive: n, n + 1, n + 2. Consecutive odd numbers: 2n + 1, 2n + 3.',
        'To prove "is a multiple of k", simplify and factor k out.',
        'Change of sign: if f(a) and f(b) have opposite signs, a root lies between a and b.',
        'Iteration: substitute each answer back into xₙ₊₁ = … (use ANS on the calculator).'],
      cards: [['Algebraic form of any odd number', '2n + 1'], ['Prove the sum of three consecutive integers is a multiple of 3', 'n + (n+1) + (n+2) = 3n + 3 = 3(n + 1)']],
      ex: 'Do 2 proof questions and 1 iteration question. Write a concluding sentence for every proof.' },
    { id: 'm-sheet', n: 'Formula sheet: what\'s given & what isn\'t', w: 2,
      pts: ['Every 2027 paper includes a formula sheet (Ofqual decision for 2025–2027). Know what is on it so you don\'t waste revision time — and so you know where to look.',
        'Both tiers: trapezium area ½(a + b)h, prism volume, circumference 2πr = πd, circle area πr², Pythagoras, sin/cos/tan, compound interest P(1 + r/100)ⁿ, P(A or B) = P(A) + P(B) − P(A and B).',
        'Higher only: quadratic formula, sine rule, cosine rule, area = ½ab sin C, P(A and B) = P(A given B) × P(B).',
        'NOT on the sheet — learn these: exact trig values, speed/density/pressure, ½bh, arc length and sector area, y = mx + c, gradient, index laws, angle rules, circle theorems (H), frequency density (H).'],
      cards: [['Is the area of a trapezium on the formula sheet?', 'Yes'], ['Is speed = distance ÷ time on the formula sheet?', 'No — learn it (and density, pressure)'],
        ['Is the quadratic formula on the Higher sheet?', 'Yes'], ['Are exact trig values (e.g. sin 30° = ½) on the sheet?', 'No — learn them'],
        ['Is sector area on the formula sheet?', 'No — θ/360 × πr²'], ['Are cone and sphere formulae given?', 'Yes — printed in the question when needed'],
        ['Is the cosine rule on the Higher sheet?', 'Yes'], ['Is y = mx + c on the formula sheet?', 'No']],
      ex: 'Look at the 2027 formula sheet, then write every formula that is NOT on it from memory and check.' },
    { id: 'm-exam', n: 'Timed practice & problem solving', w: 2,
      pts: ['Aim for about 1 mark per minute on each 80-mark, 90-minute paper.',
        'Multi-step "problem solving" questions: write what you know, what you need, and the link between them.',
        'Check answers make sense: a probability is never above 1, and a price should be sensible.',
        'After every paper, write your three most common mistakes on a sticky note and review it before the next one.'],
      cards: [['Rough time per mark', 'About 1 minute'], ['Calculator mode for trigonometry', 'Degrees (D)']],
      ex: 'Complete one full past paper under timed conditions, then mark it with the official mark scheme.' }
  ]
});
