/* Combined Science — AQA Combined Science: Trilogy 8464 (Chesterton exams page) */
RG.subjects.push({
  id: 'science', name: 'Combined Science', board: 'AQA', spec: '8464', quals: 2, share: 0.20,
  tierable: true,
  link: 'https://www.aqa.org.uk/subjects/science/gcse/combined-science-trilogy-8464',
  papers: [
    { id: 'sb1', code: '8464/B/1', name: 'Biology Paper 1', date: '2027-05-11', time: 'am', dur: 75 },
    { id: 'sc1', code: '8464/C/1', name: 'Chemistry Paper 1', date: '2027-05-17', time: 'am', dur: 75 },
    { id: 'sp1', code: '8464/P/1', name: 'Physics Paper 1', date: '2027-05-25', time: 'am', dur: 75 },
    { id: 'sb2', code: '8464/B/2', name: 'Biology Paper 2', date: '2027-06-10', time: 'am', dur: 75 },
    { id: 'sc2', code: '8464/C/2', name: 'Chemistry Paper 2', date: '2027-06-15', time: 'am', dur: 75 },
    { id: 'sp2', code: '8464/P/2', name: 'Physics Paper 2', date: '2027-06-18', time: 'am', dur: 75 }
  ],
  structure: [
    'Six papers (two each for Biology, Chemistry, Physics), 1h 15m, 70 marks, 16.7% each. Worth two GCSEs.',
    'Foundation or Higher tier. HT-only content is marked (H) here.',
    'Questions test the 21 required practicals and maths skills, as well as knowledge.'
  ],
  technique: [
    'About 1 mark per minute. Six-mark questions need a logical sequence of linked points, not a list.',
    '"Explain" = say what happens and WHY (use "because" / "so"). "Describe" = say what happens.',
    'Calculations: write the equation, substitute with units, give the answer with a unit and sensible significant figures.',
    'Graphs: read values with a ruler, draw lines of best fit smoothly, and quote data when asked to use the graph.',
    'Required practicals: know the independent, dependent and control variables and how to improve accuracy.',
    'Physics: every equation is on the Physics Equations Sheet you get in 2027 — learn the units and how to use them (see "Physics equation sheet" topic).',
  ],
  resources: [
    ['AQA Trilogy 8464 spec & past papers', 'https://www.aqa.org.uk/subjects/science/gcse/combined-science-trilogy-8464'],
    ['Physics & Maths Tutor (topic questions)', 'https://www.physicsandmathstutor.com/'],
    ['BBC Bitesize GCSE', 'https://www.bbc.co.uk/bitesize/levels/z98jmp3']
  ],
  topics: [
    /* ---------- BIOLOGY PAPER 1 ---------- */
    { id: 'b-cells', n: 'Cell structure & microscopy', p: ['sb1'], w: 3,
      pts: ['Eukaryotic cells (animal, plant) have a nucleus. Prokaryotic cells (bacteria) have no nucleus: DNA is a single loop, plus plasmids.',
        'Animal cell: nucleus, cytoplasm, cell membrane, mitochondria (respiration), ribosomes (protein synthesis).',
        'Plants also have: cell wall (cellulose, strength), chloroplasts (photosynthesis), permanent vacuole (cell sap).',
        'Magnification = image size ÷ real size. 1 mm = 1000 µm.',
        'Electron microscopes have higher magnification and resolution than light microscopes, so they show sub-cellular structures.',
        'Specialised cells: sperm (tail, many mitochondria), nerve (long, branched), muscle, root hair (large surface area), xylem, phloem.'],
      cards: [['Function of mitochondria', 'Site of aerobic respiration (releases energy)'], ['Function of ribosomes', 'Protein synthesis'],
        ['Three structures in plant cells but not animal cells', 'Cell wall, chloroplasts, permanent vacuole'],
        ['Magnification formula', 'Image size ÷ real size'], ['Where is DNA in a prokaryotic cell?', 'Single loop in the cytoplasm, plus plasmids'],
        ['Required practical: microscopy — why add a stain?', 'To make structures (e.g. nuclei) visible and give contrast']],
      ex: 'Draw and label an animal, plant and bacterial cell from memory. Then do a magnification calculation with a µm/mm conversion.' },
    { id: 'b-div', n: 'Cell division & stem cells', p: ['sb1'], w: 2,
      pts: ['Chromosomes are made of DNA. Body cells have chromosomes in pairs (23 pairs in humans).',
        'Cell cycle: the cell grows, copies DNA and organelles, then mitosis separates the chromosomes and the cytoplasm divides → 2 identical cells.',
        'Mitosis is for growth, repair and asexual reproduction.',
        'Embryonic stem cells can become most cell types. Adult stem cells (bone marrow) form some types. Plant meristems form any plant cell type for life.',
        'Therapeutic cloning: an embryo with the patient\'s genes, so no rejection. Issues: ethical/religious objections, and a risk of viral infection.'],
      cards: [['Purpose of mitosis', 'Growth, repair, asexual reproduction'], ['Where are plant stem cells found?', 'Meristems (root and shoot tips)'],
        ['Why use therapeutic cloning?', 'Cells have the patient\'s genes, so they are not rejected'], ['How many chromosome pairs in human body cells?', '23']],
      ex: 'Write a 6-mark answer: "Evaluate the use of stem cells in medicine."' },
    { id: 'b-transport', n: 'Diffusion, osmosis & active transport', p: ['sb1'], w: 3,
      pts: ['Diffusion: net movement of particles from high to low concentration. Passive. Faster with a steeper gradient, higher temperature and larger surface area.',
        'Osmosis: diffusion of WATER from a dilute to a concentrated solution through a partially permeable membrane.',
        'Active transport: movement against the concentration gradient, using energy from respiration (e.g. mineral ions into root hairs, glucose in the gut).',
        'Exchange surfaces: large surface area, thin membrane, good blood supply, ventilated (alveoli, villi, gills).',
        'Surface area : volume ratio falls as organisms get larger, so they need exchange surfaces and transport systems.',
        'Required practical (osmosis): potato cylinders in sugar solutions. Measure % change in mass and plot against concentration.'],
      cards: [['Define osmosis', 'Diffusion of water from a dilute to a more concentrated solution through a partially permeable membrane'],
        ['Why does active transport need energy?', 'It moves substances against the concentration gradient; energy comes from respiration'],
        ['Why use % change in mass in the osmosis practical?', 'Cylinders start with different masses, so % allows a fair comparison'],
        ['Adaptations of alveoli', 'Large surface area, thin walls, rich blood supply, ventilation']],
      ex: 'Do a past-paper osmosis practical question including a graph and finding where the line crosses zero.' },
    { id: 'b-digest', n: 'Digestion & enzymes', p: ['sb1'], w: 3,
      pts: ['Enzymes are biological catalysts. Lock and key: the substrate fits the active site.',
        'High temperature or wrong pH changes the active site shape — the enzyme is denatured.',
        'Carbohydrase (amylase) → starch to sugars. Protease → proteins to amino acids. Lipase → lipids to fatty acids + glycerol.',
        'Bile is made in the liver and stored in the gall bladder. It neutralises stomach acid and emulsifies fat (bigger surface area).',
        'Food tests: Benedict\'s (heat) blue → brick red for sugar. Iodine orange → blue-black for starch. Biuret blue → purple for protein. Ethanol → cloudy white for lipids.',
        'Required practical: effect of pH on amylase. Time how long until iodine stops turning blue-black.'],
      cards: [['What does protease produce?', 'Amino acids'], ['Products of lipase', 'Fatty acids and glycerol'], ['Two roles of bile', 'Neutralises stomach acid; emulsifies fats'],
        ['Test and positive result for protein', 'Biuret: blue → purple'], ['Test for starch', 'Iodine: orange-brown → blue-black'], ['Why does a denatured enzyme stop working?', 'Its active site changes shape, so the substrate no longer fits']],
      ex: 'Write the method for the amylase practical from memory (with the control variables), then check a mark scheme.' },
    { id: 'b-heart', n: 'Heart, blood & lungs', p: ['sb1'], w: 3,
      pts: ['Double circulatory system: right side pumps blood to the lungs, left side pumps it to the body.',
        'Route: vena cava → right atrium → right ventricle → pulmonary artery → lungs → pulmonary vein → left atrium → left ventricle → aorta.',
        'Pacemaker cells in the right atrium set the heart rate. Artificial pacemakers fix irregular rhythms.',
        'Arteries: thick muscular, elastic walls (high pressure). Veins: valves and a large lumen. Capillaries: walls one cell thick for exchange.',
        'Blood: red cells (haemoglobin, no nucleus, biconcave), white cells (defence), platelets (clotting), plasma (transports everything).',
        'Coronary heart disease: fatty deposits narrow the coronary arteries. Treatments: stents, statins, transplants, replacement valves.'],
      cards: [['Which side of the heart pumps to the lungs?', 'Right'], ['Why do arteries have thick walls?', 'To withstand high pressure'],
        ['Why are capillary walls one cell thick?', 'Short diffusion distance'], ['Role of platelets', 'Help the blood clot'],
        ['Advantage and disadvantage of statins', 'Lower blood cholesterol / must be taken long-term and have side effects']],
      ex: 'Trace a drop of blood through the heart aloud, then answer a 6-marker comparing stents and statins.' },
    { id: 'b-disease', n: 'Non-communicable disease & plants', p: ['sb1'], w: 2,
      pts: ['Health is physical and mental wellbeing. Risk factors: smoking (lung disease, cancer), obesity (Type 2 diabetes), alcohol (liver, brain), carcinogens and radiation (cancer).',
        'Benign tumours stay in one place. Malignant tumours invade tissue and spread in the blood (secondary tumours).',
        'Plant tissues: epidermis, palisade mesophyll (photosynthesis), spongy mesophyll (air spaces), xylem, phloem, meristem.',
        'Xylem carries water and minerals up (transpiration stream). Phloem carries dissolved sugars both ways (translocation).',
        'Stomata, opened and closed by guard cells, control gas exchange and water loss.',
        'Transpiration is faster when it is warmer, drier, windier and brighter.'],
      cards: [['Difference between benign and malignant tumours', 'Malignant tumours invade tissue and spread via the blood'], ['What does phloem transport?', 'Dissolved sugars (translocation)'],
        ['Four factors that increase transpiration', 'Temperature, light intensity, air movement, lower humidity'], ['What controls stomata?', 'Guard cells']],
      ex: 'Answer an exam question interpreting data on a risk factor (correlation vs causation) and one on transpiration.' },
    { id: 'b-infection', n: 'Infection & response', p: ['sb1'], w: 3,
      pts: ['Pathogens: viruses (measles, HIV, tobacco mosaic virus), bacteria (Salmonella, gonorrhoea), fungi (rose black spot), protists (malaria — spread by mosquitoes).',
        'Spread by air, water or direct contact. Reduce by hygiene, isolation, destroying vectors, vaccination.',
        'Non-specific defences: skin, nose hairs and mucus, cilia in the trachea, stomach acid.',
        'White blood cells: phagocytosis, producing antibodies, producing antitoxins.',
        'Vaccination: dead or inactive pathogen → white cells make antibodies and memory cells → fast response later. Herd immunity protects others.',
        'Antibiotics kill bacteria but NOT viruses. Resistance is increasing. Drug testing: pre-clinical (cells, animals) → clinical trials, double-blind with a placebo.',
        'Drug origins: digitalis from foxgloves (heart drug), aspirin from willow (painkiller), penicillin discovered by Alexander Fleming from Penicillium mould. Most new drugs are now made by chemists.'],
      cards: [['Why can\'t antibiotics treat viral infections?', 'Viruses live inside cells; antibiotics only kill bacteria'], ['Three ways white blood cells defend us', 'Phagocytosis, antibodies, antitoxins'],
        ['What is a double-blind trial?', 'Neither patients nor doctors know who gets the drug or the placebo'], ['How is malaria spread?', 'By mosquitoes (vector), protist pathogen'],
        ['How does vaccination work?', 'Inactive pathogen triggers antibodies and memory cells, so a later infection is fought quickly'],
        ['Where do digitalis, aspirin and penicillin come from?', 'Foxgloves, willow, Penicillium mould (Fleming)']],
      ex: 'Make a table of the 7 named diseases (pathogen type, spread, symptoms, control), then do one 6-marker on vaccination.' },
    { id: 'b-energy', n: 'Photosynthesis & respiration', p: ['sb1'], w: 3,
      pts: ['Photosynthesis: carbon dioxide + water → glucose + oxygen (light, chlorophyll). 6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂. Endothermic.',
        'Limiting factors: light intensity, CO₂ concentration, temperature, amount of chlorophyll.',
        'Inverse square law (H): light intensity ∝ 1/distance².',
        'Glucose is used for respiration, starch (storage), cellulose, fats/oils, and amino acids (with nitrate ions).',
        'Aerobic respiration: glucose + oxygen → carbon dioxide + water. Anaerobic in muscles: glucose → lactic acid (oxygen debt, H). In yeast: glucose → ethanol + carbon dioxide.',
        'Required practical: pondweed at different distances from a lamp — count bubbles or measure O₂ volume.'],
      cards: [['Word equation for photosynthesis', 'Carbon dioxide + water → glucose + oxygen'], ['Word equation for aerobic respiration', 'Glucose + oxygen → carbon dioxide + water'],
        ['Anaerobic respiration in muscles produces…', 'Lactic acid'], ['Anaerobic respiration in yeast produces…', 'Ethanol and carbon dioxide'],
        ['Four limiting factors of photosynthesis', 'Light intensity, CO₂ concentration, temperature, chlorophyll'], ['Why does a graph of rate vs light intensity level off?', 'Another factor (CO₂ or temperature) becomes limiting']],
      ex: 'Do a limiting-factor graph question and a 6-marker describing the pondweed practical.' },

    /* ---------- BIOLOGY PAPER 2 ---------- */
    { id: 'b-nerves', n: 'Nervous system & reaction time', p: ['sb2'], w: 2, from: '2027-01-04',
      pts: ['Homeostasis keeps internal conditions (blood glucose, body temperature, water levels) steady. Control systems have receptors, coordination centres (brain, spinal cord, pancreas) and effectors.',
        'Stimulus → receptor → sensory neurone → relay neurone (CNS) → motor neurone → effector → response.',
        'Reflexes are automatic and rapid, and they do not involve the conscious brain. Synapses pass signals chemically across a gap.',
        'The CNS is the brain and spinal cord.',
        'Required practical: ruler-drop reaction time. Repeat, calculate the mean, control the hand and the distractions.'],
      cards: [['Order of a reflex arc', 'Receptor → sensory → relay → motor → effector'], ['How is a signal passed across a synapse?', 'Chemicals diffuse across the gap'],
        ['Why are reflexes fast?', 'They bypass the conscious part of the brain']],
      ex: 'Label a reflex arc from memory and answer a reaction-time practical question.' },
    { id: 'b-hormones', n: 'Hormones, blood glucose & reproduction', p: ['sb2'], w: 3, from: '2027-01-04',
      pts: ['Endocrine glands release hormones into the blood. The pituitary is the "master gland".',
        'Blood glucose too high → pancreas releases insulin → cells take up glucose, liver stores it as glycogen. Too low → glucagon (H) converts glycogen back.',
        'Type 1 diabetes: the pancreas makes no insulin → injections. Type 2: cells stop responding → diet and exercise. Obesity is a risk factor.',
        'Menstrual cycle: FSH (egg matures, oestrogen made), oestrogen (lining builds), LH (ovulation), progesterone (maintains lining).',
        'Contraception: hormonal (pill, implant, injection) and non-hormonal (condoms, diaphragm, IUD, sterilisation, abstinence).',
        'H: thyroxine and adrenaline, negative feedback, and using hormones to treat infertility (IVF).'],
      cards: [['Hormone that lowers blood glucose', 'Insulin'], ['Difference between Type 1 and Type 2 diabetes', 'Type 1: no insulin made. Type 2: cells don\'t respond to insulin'],
        ['Which hormone triggers ovulation?', 'LH'], ['Role of FSH', 'Causes an egg to mature and stimulates oestrogen production'], ['Where is glycogen stored?', 'Liver (and muscles)']],
      ex: 'Draw the blood-glucose feedback loop, then do a 6-marker comparing hormonal and non-hormonal contraception.' },
    { id: 'b-genetics', n: 'Inheritance & variation', p: ['sb2'], w: 3,
      pts: ['DNA is a double helix polymer. A gene codes for a particular protein. The genome is all of an organism\'s genetic material.',
        'Meiosis makes 4 genetically different gametes with half the chromosomes. Fertilisation restores the full number.',
        'Dominant allele shows with one copy. Recessive needs two. Homozygous = same alleles, heterozygous = different.',
        'Punnett squares give probabilities. Cystic fibrosis is recessive. Polydactyly is dominant.',
        'Sex: XX female, XY male — always a 50% chance of either.',
        'Embryo screening raises ethical, economic and social issues.'],
      cards: [['Define allele', 'A different form of the same gene'], ['Genotype vs phenotype', 'Genotype = alleles; phenotype = characteristic shown'],
        ['Two carriers (Ff × Ff) of cystic fibrosis: chance of an affected child?', '25% (1 in 4)'], ['How many cells does meiosis produce?', 'Four genetically different gametes'],
        ['Is polydactyly dominant or recessive?', 'Dominant']],
      ex: 'Do 3 Punnett-square questions (including a family tree) and one embryo-screening evaluation.' },
    { id: 'b-evolution', n: 'Evolution, breeding & classification', p: ['sb2'], w: 2,
      pts: ['Natural selection: variation → better-adapted individuals survive and breed → pass on alleles → over time the species changes.',
        'Evidence: fossils, antibiotic-resistant bacteria.',
        'Selective breeding: choose parents with desired traits over many generations. Risk: inbreeding and reduced variation.',
        'Genetic engineering: a gene is transferred into another organism (e.g. human insulin gene into bacteria, GM crops).',
        'Classification: Linnaean system (kingdom … species, binomial names). Woese\'s three domains: Archaea, Bacteria, Eukaryota.',
        'Extinction causes: new predators, disease, competition, environmental change, catastrophic events.'],
      cards: [['Why are antibiotic-resistant bacteria evidence for evolution?', 'Resistant bacteria survive and reproduce, so resistance spreads — natural selection seen quickly'],
        ['One risk of selective breeding', 'Inbreeding — reduced variation, vulnerable to disease'], ['Woese\'s three domains', 'Archaea, Bacteria, Eukaryota'],
        ['Example of genetic engineering', 'Human insulin gene put into bacteria']],
      ex: 'Write a 6-mark explanation of how antibiotic resistance develops (natural selection steps in order).' },
    { id: 'b-ecology', n: 'Ecology & biodiversity', p: ['sb2'], w: 3, from: '2026-09-02',
      pts: ['Community = all populations in a habitat. Interdependence: species depend on each other for food, shelter, pollination.',
        'Abiotic factors: light, temperature, moisture, soil pH and minerals, wind, CO₂, O₂. Biotic: food, predators, pathogens, competition.',
        'Adaptations: structural, behavioural, functional. Extremophiles live in extreme conditions.',
        'Predator–prey cycles: predator numbers peak after prey numbers.',
        'Required practical: quadrats (random sampling for abundance) and transects (how distribution changes).',
        'Levels of organisation: producers (photosynthesise) → primary → secondary → tertiary consumers; feeding relationships in food chains.',
        'Carbon cycle: photosynthesis removes CO₂; respiration, decomposition and combustion return it. Water cycle: evaporation, condensation, precipitation.',
        'Humans reduce biodiversity through waste, pollution, land use, deforestation (peat bogs, tropical forest) and global warming. Protect it with breeding programmes, hedgerows, reduced deforestation and recycling.'],
      cards: [['Three abiotic factors', 'e.g. light intensity, temperature, soil pH'], ['What is a quadrat used for?', 'Estimating population size / abundance by random sampling'],
        ['What is a transect used for?', 'Showing how distribution changes across a habitat'], ['Two processes that return CO₂ to the air', 'Respiration and combustion (also decomposition)'],
        ['Why does the predator peak come after the prey peak?', 'Predators need time to feed and reproduce after food increases']],
      ex: 'Do a quadrat calculation (mean per quadrat × area) and a 6-marker on the carbon cycle.' },

    /* ---------- CHEMISTRY PAPER 1 ---------- */
    { id: 'c-atoms', n: 'Atoms, the periodic table & separating', p: ['sc1'], w: 3,
      pts: ['Proton: charge +1, mass 1. Neutron: 0, mass 1. Electron: −1, very small mass. Atomic number = protons. Mass number = protons + neutrons.',
        'Isotopes: same number of protons, different number of neutrons.',
        'Model of the atom: tiny spheres → discovery of the electron led to the plum pudding model → alpha scattering showed a small positive nucleus (nuclear model) → Bohr: electrons in shells → Chadwick provided evidence for the neutron.',
        'Electron shells: 2, 8, 8. Group number = outer electrons. Period = number of shells.',
        'Group 1: react with water → metal hydroxide + hydrogen, more reactive down the group. Group 7: less reactive down the group, displacement reactions. Group 0: unreactive (full outer shell).',
        'Separating mixtures: filtration, crystallisation, simple and fractional distillation, chromatography. Mendeleev left gaps for undiscovered elements.'],
      cards: [['Define isotope', 'Atoms of the same element with different numbers of neutrons'], ['What did the alpha-scattering experiment show?', 'Mass is concentrated in a small, positive nucleus'],
        ['Electronic structure of sodium (11)', '2, 8, 1'], ['Why does Group 1 reactivity increase down the group?', 'Outer electron is further from the nucleus, so it is lost more easily'],
        ['Why did Mendeleev leave gaps?', 'For elements not yet discovered, so patterns lined up'], ['Group 1 metal + water →', 'Metal hydroxide + hydrogen']],
      ex: 'Write electron structures for elements 1–20, then do a 6-marker on the development of the atomic model.' },
    { id: 'c-bonding', n: 'Bonding, structure & properties', p: ['sc1'], w: 3,
      pts: ['Ionic: metal + non-metal, electrons transferred, giant lattice, high melting point, conducts when molten or dissolved.',
        'Covalent: non-metals share pairs of electrons. Simple molecules have weak intermolecular forces → low boiling points, don\'t conduct.',
        'Diamond: each C has 4 covalent bonds — very hard, very high melting point, no conduction.',
        'Graphite: each C has 3 bonds, layers slide, delocalised electrons → conducts. Graphene: a single layer. Fullerenes: hollow cages and tubes.',
        'Metallic bonding: positive ions in a sea of delocalised electrons → conducts, malleable. Alloys are harder because different-sized atoms distort the layers.',
        'Polymers: very long molecules joined by strong covalent bonds. Intermolecular forces between them are relatively strong, so they are solid at room temperature.',
        'Draw dot-and-cross diagrams for NaCl, MgO, H₂, Cl₂, H₂O, NH₃, CH₄, HCl.'],
      cards: [['Why does graphite conduct electricity?', 'Each carbon has one delocalised electron that can move'], ['Why are alloys harder than pure metals?', 'Different-sized atoms distort the layers so they cannot slide'],
        ['Why does ionic NaCl have a high melting point?', 'Strong electrostatic forces between oppositely charged ions in a giant lattice need lots of energy to overcome'],
        ['Why do simple molecules have low boiling points?', 'Weak intermolecular forces, not covalent bonds, are broken'], ['When does an ionic compound conduct?', 'When molten or dissolved (ions free to move)']],
      ex: 'Draw 4 dot-and-cross diagrams from memory, then answer a "compare diamond and graphite" 6-marker.' },
    { id: 'c-quant', n: 'Quantitative chemistry', p: ['sc1'], w: 2,
      pts: ['Conservation of mass: total mass of reactants = total mass of products. Mass "lost" is usually a gas escaping.',
        'Relative formula mass (Mr) = sum of the relative atomic masses.',
        'H: moles = mass ÷ Mr. One mole contains 6.02 × 10²³ particles (Avogadro constant).',
        'H: reacting masses — use the mole ratio from the balanced equation. The limiting reactant is used up first.',
        'Concentration (g/dm³) = mass ÷ volume (dm³). 1 dm³ = 1000 cm³.'],
      cards: [['Mr of CO₂ (C = 12, O = 16)', '44'], ['Moles in 88 g of CO₂', '2 mol'], ['Concentration of 10 g in 250 cm³', '40 g/dm³'], ['Avogadro constant', '6.02 × 10²³']],
      ex: 'Do 5 calculations: Mr, % mass, concentration, and (H) two reacting-mass questions.' },
    { id: 'c-changes', n: 'Chemical changes, acids & electrolysis', p: ['sc1'], w: 3,
      pts: ['Reactivity series: K, Na, Li, Ca, Mg, (C), Zn, Fe, (H), Cu. Metals below carbon are extracted by reduction with carbon.',
        'Oxidation is gain of oxygen (H: loss of electrons — OIL RIG).',
        'Acid + metal → salt + hydrogen. Acid + alkali → salt + water. Acid + carbonate → salt + water + carbon dioxide. Neutralisation: H⁺ + OH⁻ → H₂O.',
        'Required practical: making a soluble salt — add excess insoluble base to acid, filter, evaporate, crystallise.',
        'Electrolysis: positive ions to the cathode (−), negative ions to the anode (+). Aluminium from aluminium oxide dissolved in cryolite (lower melting point). Carbon anodes burn away.',
        'Aqueous solutions: hydrogen forms at the cathode if the metal is more reactive than hydrogen. Oxygen forms at the anode unless a halide is present.',
        'Required practical: electrolysis of aqueous solutions with inert electrodes — identify the product at each electrode.'],
      cards: [['Acid + carbonate →', 'Salt + water + carbon dioxide'], ['OIL RIG', 'Oxidation Is Loss, Reduction Is Gain (of electrons)'],
        ['Why is aluminium oxide dissolved in cryolite?', 'Lowers the melting point, saving energy'], ['Electrolysis of NaCl solution: product at cathode', 'Hydrogen'],
        ['Why add excess base when making a salt?', 'To make sure all the acid reacts'], ['Why must carbon anodes be replaced?', 'They react with oxygen to form CO₂']],
      ex: 'Write the salt-making method from memory, then predict electrolysis products for 4 solutions.' },
    { id: 'c-energy', n: 'Energy changes', p: ['sc1'], w: 2,
      pts: ['Exothermic: energy released, temperature rises (combustion, neutralisation, hand warmers).',
        'Endothermic: energy taken in, temperature falls (thermal decomposition, sports injury packs).',
        'Reaction profiles: activation energy is the minimum energy needed to react. Exothermic products are lower than reactants.',
        'H: bond energy calculation — energy to break bonds − energy released making bonds. A negative result means exothermic.',
        'Required practical: temperature change in a polystyrene cup with a lid. Vary the concentration or amount of reactant.'],
      cards: [['Is neutralisation exo- or endothermic?', 'Exothermic'], ['Define activation energy', 'Minimum energy particles need to react'],
        ['Why use a polystyrene cup with a lid?', 'Reduces energy lost to the surroundings'], ['Bond energy: breaking > making means…', 'Endothermic overall']],
      ex: 'Sketch both reaction profiles from memory and do one bond-energy calculation (H).' },

    /* ---------- CHEMISTRY PAPER 2 ---------- */
    { id: 'c-rates', n: 'Rates & equilibrium', p: ['sc2'], w: 3,
      pts: ['Rate = amount of reactant used (or product made) ÷ time.',
        'Collision theory: particles must collide with at least the activation energy. More frequent successful collisions = faster reaction.',
        'Rate increases with temperature, concentration or pressure, surface area, and a catalyst (a catalyst lowers the activation energy and is not used up).',
        'Measure it by gas volume (syringe), mass loss, or a "disappearing cross" (sodium thiosulfate + acid). H: gradient of a tangent gives the rate at a point.',
        'Reversible reactions ⇌ reach equilibrium in a closed system (forward rate = backward rate).',
        'H: Le Chatelier — raising the temperature favours the endothermic direction. Raising the pressure favours the side with fewer gas molecules.'],
      cards: [['How does a catalyst increase rate?', 'Provides a pathway with lower activation energy'], ['Why does higher temperature increase rate?', 'Particles move faster → more frequent collisions, and more have enough energy'],
        ['Define equilibrium', 'Forward and reverse reactions happen at the same rate in a closed system'], ['Why does powder react faster than lumps?', 'Larger surface area → more frequent collisions'],
        ['How do you find the rate at a point on a curve? (H)', 'Draw a tangent and calculate its gradient']],
      ex: 'Plot a rate graph from data, draw a tangent (H), and write a 6-marker on the thiosulfate practical.' },
    { id: 'c-organic', n: 'Organic chemistry & crude oil', p: ['sc2'], w: 2, from: '2026-09-02',
      pts: ['Crude oil is a mixture of hydrocarbons, mostly alkanes CₙH₂ₙ₊₂: methane, ethane, propane, butane.',
        'Fractional distillation: heat and vaporise; fractions condense at different heights. Short chains at the top — low boiling point, runny, very flammable.',
        'Complete combustion: hydrocarbon + oxygen → carbon dioxide + water.',
        'Cracking (catalytic or steam) breaks long alkanes into shorter alkanes and alkenes, which are more useful and in higher demand.',
        'Alkenes have a C=C double bond. Test: bromine water goes from orange to colourless.'],
      cards: [['General formula of alkanes', 'CₙH₂ₙ₊₂'], ['Test for alkenes', 'Bromine water: orange → colourless'], ['Why crack long hydrocarbons?', 'To meet demand for shorter, more useful fuels and to make alkenes for polymers'],
        ['Properties of short-chain hydrocarbons', 'Low boiling point, low viscosity, very flammable'], ['Products of complete combustion', 'Carbon dioxide and water']],
      ex: 'Draw and explain the fractionating column, then balance 3 combustion and cracking equations.' },
    { id: 'c-analysis', n: 'Chemical analysis', p: ['sc2'], w: 2, from: '2026-11-02',
      pts: ['A pure substance is a single element or compound, with a sharp melting and boiling point.',
        'Formulations are mixtures in exact proportions for a purpose (paint, medicines, fuels).',
        'Chromatography: Rf = distance moved by the spot ÷ distance moved by the solvent. A pure substance gives one spot. Draw the start line in pencil.',
        'Gas tests: hydrogen — squeaky pop with a lit splint. Oxygen — relights a glowing splint. CO₂ — limewater turns milky. Chlorine — bleaches damp litmus paper.'],
      cards: [['Rf formula', 'Distance moved by spot ÷ distance moved by solvent'], ['Test for oxygen', 'Relights a glowing splint'], ['Test for chlorine', 'Bleaches damp litmus paper white'],
        ['Why draw the chromatography baseline in pencil?', 'Pencil doesn\'t dissolve in the solvent'], ['How do you tell a pure substance?', 'Sharp, specific melting/boiling point']],
      ex: 'Calculate 3 Rf values and answer the chromatography required-practical questions.' },
    { id: 'c-atmos', n: 'The atmosphere', p: ['sc2'], w: 2, from: '2027-01-04',
      pts: ['Early atmosphere: volcanoes released mainly CO₂, with water vapour and nitrogen. Water vapour condensed to form oceans.',
        'Algae and plants photosynthesised → oxygen increased and CO₂ decreased. CO₂ was locked into sedimentary rocks and fossil fuels.',
        'Now: about 80% nitrogen, about 20% oxygen, small amounts of CO₂, water vapour and noble gases.',
        'Greenhouse gases (CO₂, methane, water vapour) absorb infrared radiation. Human activity increases CO₂ (combustion, deforestation) and methane (farming, landfill).',
        'Pollutants: carbon monoxide (toxic, incomplete combustion), sulfur dioxide and nitrogen oxides (acid rain, breathing problems), soot particulates (global dimming).',
        'Carbon footprint = total greenhouse gases over a product\'s life cycle.'],
      cards: [['Main gas in the early atmosphere', 'Carbon dioxide'], ['Why did oxygen increase?', 'Photosynthesis by algae and plants'], ['Why is carbon monoxide dangerous?', 'Toxic — stops blood carrying oxygen'],
        ['Two human sources of methane', 'Farming (cattle, rice) and landfill'], ['Rough composition of air today', '~80% nitrogen, ~20% oxygen']],
      ex: 'Write a 6-marker on how the atmosphere has changed, then a climate-change evaluation.' },
    { id: 'c-resources', n: 'Using resources & water', p: ['sc2'], w: 2, from: '2027-01-04',
      pts: ['Potable water is safe to drink. UK fresh water: filtered, then sterilised (chlorine, ozone or UV). Sea water: desalination by distillation or reverse osmosis (costly in energy).',
        'Waste water: screening → sedimentation → anaerobic digestion of sludge, aerobic treatment of effluent.',
        'H: phytomining (plants absorb metal, then burn to ash) and bioleaching (bacteria) extract low-grade copper ores.',
        'Life cycle assessment: raw materials, manufacture, use, disposal.',
        'Reduce, reuse, recycle to save resources and energy.',
        'Required practical: analyse and purify water — test pH, evaporate to find dissolved solids, distil.'],
      cards: [['Two ways to sterilise water', 'Chlorine, ozone or UV light'], ['Why is desalination expensive?', 'Needs lots of energy'], ['Four stages of a life cycle assessment', 'Raw materials, manufacture, use, disposal'],
        ['What is phytomining? (H)', 'Plants absorb metal compounds; burned to give ash rich in metal']],
      ex: 'Answer a life-cycle-assessment comparison question (e.g. paper vs plastic bags).' },

    /* ---------- PHYSICS PAPER 1 ---------- */
    { id: 'p-energy', n: 'Energy', p: ['sp1'], w: 3,
      pts: ['Energy stores: kinetic, gravitational potential, elastic, thermal, chemical, magnetic, electrostatic, nuclear.',
        'Kinetic energy = ½mv². GPE = mgh. Elastic PE = ½ke².',
        'Specific heat capacity: ΔE = mcΔθ. Required practical: heat a block with an immersion heater, measure energy in and temperature rise.',
        'Power = energy ÷ time = work done ÷ time. Efficiency = useful output ÷ total input.',
        'Reduce unwanted transfers with lubrication and thermal insulation. Thicker, lower-conductivity walls lose heat more slowly.',
        'Resources: renewable (solar, wind, hydro, tidal, wave, geothermal, biofuel) vs non-renewable (coal, oil, gas, nuclear). Compare reliability, cost and environmental impact.'],
      cards: [['Kinetic energy equation', 'Eₖ = ½mv²'], ['GPE equation', 'Eₚ = mgh'], ['Specific heat capacity equation', 'ΔE = mcΔθ'],
        ['Efficiency', 'Useful output ÷ total input'], ['One advantage and one disadvantage of wind power', 'Renewable, no CO₂ / unreliable and visual impact'], ['Unit of power', 'Watt (W) = J/s']],
      ex: 'Do 5 energy calculations (including rearranging ½mv²) and one 6-marker comparing energy resources.' },
    { id: 'p-elec', n: 'Electricity', p: ['sp1'], w: 3,
      pts: ['Charge Q = It. Potential difference V = IR. Power P = VI = I²R. Energy E = Pt = QV.',
        'Series: same current everywhere, p.d. shared, R total = R₁ + R₂. Parallel: same p.d. on each branch, currents add, total R is less than the smallest.',
        'I–V graphs: fixed resistor is a straight line through the origin. Filament lamp curves (resistance rises with temperature). Diode lets current flow one way only.',
        'LDR: resistance falls as light increases. Thermistor: resistance falls as temperature increases.',
        'UK mains: 230 V, 50 Hz a.c. Live (brown), neutral (blue), earth (green/yellow). Fuses and earthing are for safety.',
        'National Grid: step-up transformers raise the p.d. (lower current, less energy loss); step-down transformers make it safe for homes.',
        'Required practicals: resistance (length of a wire; resistors in series and parallel) and I–V characteristics of a resistor, filament lamp and diode.'],
      cards: [['V = ?', 'IR'], ['Resistance in parallel is…', 'Less than the smallest individual resistor'], ['What happens to an LDR in bright light?', 'Resistance decreases'],
        ['Colour of the live wire', 'Brown'], ['Why does the National Grid use high voltage?', 'Lower current → less energy lost as heat in cables'], ['UK mains frequency and p.d.', '50 Hz, 230 V']],
      ex: 'Do 4 circuit calculations, then sketch the three I–V graphs from memory and explain the filament lamp.' },
    { id: 'p-particles', n: 'Particle model of matter', p: ['sp1'], w: 2,
      pts: ['Density ρ = m ÷ V. Required practical: regular shapes (measure dimensions) and irregular shapes (displacement / eureka can).',
        'Solids → liquids → gases: particles get further apart and move more. Density is usually lowest as a gas.',
        'Internal energy = kinetic + potential energy of the particles. Heating raises temperature OR changes state.',
        'Specific latent heat: E = mL. Fusion = melting/freezing. Vaporisation = boiling/condensing. Temperature stays constant during a change of state.',
        'Gas pressure: particles collide with the walls. Hotter at constant volume → faster particles → more frequent, harder collisions → higher pressure.'],
      cards: [['Density equation', 'ρ = m/V'], ['Why is temperature constant while ice melts?', 'Energy breaks bonds (raises potential energy) instead of kinetic energy'],
        ['Specific latent heat equation', 'E = mL'], ['Why does gas pressure rise when heated in a sealed container?', 'Particles move faster, hitting the walls more often and harder']],
      ex: 'Describe both density practicals, then do 2 latent-heat calculations from a heating curve.' },
    { id: 'p-atomic', n: 'Atomic structure & radiation', p: ['sp1'], w: 3,
      pts: ['Atom radius about 1 × 10⁻¹⁰ m. The nucleus is tiny, containing protons and neutrons.',
        'Alpha: helium nucleus (2p + 2n), most ionising, stopped by paper or a few cm of air. Beta: fast electron, stopped by a few mm of aluminium. Gamma: EM wave, most penetrating (thick lead or concrete).',
        'Nuclear equations: alpha lowers the mass number by 4 and the atomic number by 2. Beta raises the atomic number by 1.',
        'Half-life: time for half the nuclei (or the activity) to halve. Activity is measured in becquerels (Bq).',
        'Contamination = radioactive atoms get on or into something. Irradiation = exposed to radiation (does not become radioactive).',
        'The plum pudding model was replaced after alpha scattering showed a small, dense, positive nucleus.'],
      cards: [['Which radiation is most ionising?', 'Alpha'], ['What stops beta radiation?', 'A few mm of aluminium'], ['Define half-life', 'Time for the number of unstable nuclei (or activity) to halve'],
        ['Alpha decay changes mass and atomic number by…', 'Mass −4, atomic number −2'], ['Contamination vs irradiation', 'Contamination: radioactive material gets on or in an object. Irradiation: object is exposed but not made radioactive'],
        ['Activity 800 Bq, half-life 2 days. Activity after 6 days?', '100 Bq']],
      ex: 'Do 3 half-life questions (one from a graph) and complete 2 nuclear equations.' },

    /* ---------- PHYSICS PAPER 2 ---------- */
    { id: 'p-forces', n: 'Forces & motion', p: ['sp2'], w: 3, from: '2026-09-02',
      pts: ['Scalars have size only (speed, distance, mass). Vectors have size and direction (velocity, displacement, force).',
        'Weight W = mg (g = 9.8 N/kg). Work done W = Fs. Hooke\'s law F = ke (up to the limit of proportionality) — required practical with springs.',
        'Distance–time graph gradient = speed. Velocity–time graph gradient = acceleration; area under it = distance.',
        'Acceleration a = Δv ÷ t. Also v² − u² = 2as.',
        'Newton 1: zero resultant force → constant velocity. Newton 2: F = ma (required practical with a trolley). Newton 3: equal and opposite forces on different objects.',
        'Stopping distance = thinking + braking distance. Tiredness, drugs and alcohol increase thinking distance. Wet or icy roads, worn tyres and brakes increase braking distance.',
        'H: momentum p = mv, and momentum is conserved in collisions.'],
      cards: [['Newton\'s second law', 'F = ma'], ['Gradient of a velocity–time graph', 'Acceleration'], ['Weight equation', 'W = mg'],
        ['Factors affecting thinking distance', 'Speed, tiredness, drugs, alcohol, distractions'], ['Hooke\'s law', 'F = ke'], ['Momentum equation (H)', 'p = mv']],
      ex: 'Do 5 motion calculations (including v² − u² = 2as) and a 6-marker on stopping distances.' },
    { id: 'p-waves', n: 'Waves & the EM spectrum', p: ['sp2'], w: 3,
      pts: ['Transverse: oscillations perpendicular to the direction of travel (light, water waves). Longitudinal: parallel — compressions and rarefactions (sound).',
        'Wave speed v = fλ. Period T = 1/f.',
        'Required practicals: ripple tank and a vibrating string to measure wave speed; infrared emitted from different surfaces (matt black emits and absorbs best).',
        'EM spectrum (increasing frequency): radio, microwaves, infrared, visible, ultraviolet, X-rays, gamma.',
        'Uses: radio (TV/radio), microwaves (satellites, cooking), infrared (heaters, cameras), visible (fibre optics), UV (tanning, energy-efficient lamps), X-rays and gamma (imaging, sterilising, treating cancer).',
        'Dangers: UV causes skin ageing and cancer. X-rays and gamma are ionising — they can cause mutations and cancer.'],
      cards: [['Wave speed equation', 'v = fλ'], ['Order of the EM spectrum', 'Radio, micro, IR, visible, UV, X-ray, gamma'], ['Transverse vs longitudinal', 'Perpendicular vs parallel oscillations'],
        ['Best emitter of infrared', 'Matt black surface'], ['Frequency 50 Hz, wavelength 2 m — speed?', '100 m/s'], ['Two uses of microwaves', 'Satellite communications, cooking']],
      ex: 'Recall the EM spectrum with a use and a danger for each, then do 3 v = fλ calculations with standard form.' },
    { id: 'p-magnet', n: 'Magnetism & electromagnetism', p: ['sp2'], w: 2, from: '2027-01-04',
      pts: ['Like poles repel, unlike poles attract. Field lines go from north to south. Induced magnets are only magnetic inside a field.',
        'A compass points along the field. The Earth has a magnetic field.',
        'A current in a wire makes a circular field. A solenoid gives a strong, uniform field inside; adding an iron core makes an electromagnet.',
        'H: motor effect F = BIl. Fleming\'s left-hand rule — thuMb = Motion, First finger = Field, seCond finger = Current.',
        'H: a coil carrying current in a magnetic field turns — the electric motor.'],
      cards: [['Direction of field lines', 'North to south'], ['How can you make an electromagnet stronger?', 'More current, more turns, add an iron core'],
        ['Fleming\'s left-hand rule fingers (H)', 'Thumb: motion. First: field. Second: current'], ['Motor effect equation (H)', 'F = BIl']],
      ex: 'Draw field patterns (bar magnet, wire, solenoid) and do 2 F = BIl questions (H).' },
    { id: 'p-equations', n: 'Physics equation sheet — using it well', p: ['sp1', 'sp2'], w: 3,
      pts: ['In 2027 every Physics paper comes with the AQA Physics Equations Sheet as an insert (Ofqual decision for 2025–2027). It lists EVERY equation on the course, so you do not have to memorise them.',
        'What the sheet does NOT give you: the units, which equation to pick, how to rearrange it, unit conversions, and the value of g (it is given in the question, e.g. 9.8 N/kg).',
        'So the skills are: spot the quantities in the question → find the equation with those symbols → rearrange → convert units (g → kg, kJ → J, minutes → s, cm → m) → answer with the correct unit.',
        'Know your symbols: Eₖ kinetic energy, Eₚ GPE, Eₑ elastic PE, Q charge, I current, V potential difference, R resistance, P power, ρ density, λ wavelength, f frequency, p momentum, θ temperature.',
        'Prefixes: k = ×1000, M = ×1 000 000, m = ÷1000, µ = ÷1 000 000.',
        'Practise with the real sheet next to you — AQA publishes the 2027 version so you can get used to where everything is.'],
      cards: [['Unit of energy', 'joule (J)'], ['Unit of power', 'watt (W)'], ['Unit of charge', 'coulomb (C)'], ['Unit of potential difference', 'volt (V)'],
        ['Unit of resistance', 'ohm (Ω)'], ['Unit of force', 'newton (N)'], ['Unit of momentum (H)', 'kg m/s'], ['Unit of spring constant', 'N/m'],
        ['Unit of specific heat capacity', 'J/kg °C'], ['Unit of specific latent heat', 'J/kg'], ['Unit of density', 'kg/m³'], ['Unit of frequency', 'hertz (Hz)'],
        ['Unit of acceleration', 'm/s²'], ['Unit of magnetic flux density (H)', 'tesla (T)'], ['What does the prefix k mean? And m?', 'k = ×1000 (kilo); m = ÷1000 (milli)'],
        ['Do you need to memorise physics equations for 2027?', 'No — they are all on the equation sheet. You DO need the units and how to use them']],
      ex: 'Print or open the 2027 AQA Physics Equations Sheet. Do 8 mixed calculations using only the sheet — each answer with a unit.' },
    { id: 'p-skills', n: 'Required practicals & working scientifically', p: ['sb1', 'sc1', 'sp1', 'sb2', 'sc2', 'sp2'], w: 2,
      pts: ['Independent variable = what you change. Dependent = what you measure. Control = kept the same.',
        'Accurate = close to the true value. Precise = results close together. Repeatable = same person, same method. Reproducible = different person or method.',
        'Resolution = smallest change an instrument can show. Uncertainty ≈ half the range of repeats.',
        'Anomalies: identify, explain and exclude them from the mean. Hazards: state the risk and a precaution.',
        '21 required practicals in Trilogy (Bio 7, Chem 6, Phys 8). For each, know the method, variables, hazards and improvements.'],
      cards: [['Define precise', 'Repeat results are close together'], ['Define reproducible', 'Similar results obtained by a different person or with different equipment'],
        ['How do you estimate uncertainty?', 'Half the range of the repeat readings'], ['Independent variable', 'The variable you deliberately change']],
      ex: 'Pick one required practical and write its full method, variables, risks and one improvement. Check it against a mark scheme.' }
  ]
});
